### ISSUE TITLE
Add date information under release version number in release-changelog

### ISSUE THREAD

**Issue by rubiatoEJ** [dxatscale/sfpowerscripts#1006]
Describe the feature:

After every successful deployments, it will automatically generate release-changelog, this feature request is if it is possible to add a date information maybe beside or under release version number in release-changelog

Sample in the screenshot below:
![image](https://user-images.githubusercontent.com/88638065/172107580-cf3af8c8-210b-4a16-afa6-beba5ffc73e6.png)

Will it be possible to add a `date` when new release version will be generated for release-changelog?

**Comment by vuha-acn** [comment]
@rubiatoEJ - Can you provide exactly the date format and location in a sample MD excerpt so that it's clear on the feature request?

**Comment by rubiatoEJ** [comment]
> @rubiatoEJ - Can you provide exactly the date format and location in a sample MD excerpt so that it's clear on the feature request?

@vuha-acn I was thinking of something like this:
![image](https://user-images.githubusercontent.com/88638065/172112042-8504423e-c38c-4a54-bc07-593baa58d911.png)
maybe below the release version number?

for the date format, I'm thinking with using this format: `DD/MM/YYYY`
but maybe we can use a global / international standard of date format.

**Comment by vuha-acn** [comment]
@rubiatoEJ - Releases get generated but not deployed across all environments or production the same date though.  Does this matter? What about when releases are abandoned?

**Comment by azlam-abdulsalam** [comment]
A first deployed date is currently added to Release Changelog from December 22. Closing this issue
