### ISSUE TITLE
sfp cli errors out

### ISSUE THREAD

**Issue by sumanthreddybolledla** [dxatscale/sfpowerscripts#1035]
**Describe the bug**
sfp cli fails to run due to dependency error

**To Reproduce**
run the command "sfp init" or "sfp org"

**Expected behavior**
sfp should not error and should be able to proceed to next steps

**Screenshots**
<img width="499" alt="2022-06-10 14_13_12-sfdx-project json - SalesforceDigitalPharmacy - Visual Studio Code" src="https://user-images.githubusercontent.com/19957368/173126371-d198edca-9607-4754-9b60-d14edeca5b6d.png">

**Platform Details (please complete the following information):**
 - OS: Windows
 - Version [e.g. CLI Version  eg: 1.6.6] @dxatscale/sfp-cli/2.3.8 win32-x64 node-v16.14.2
 - Salesforce CLI(sfdx cli) Version: sfdx-cli/7.147.1 win32-x64 node-v16.14.2
 - CI Platform: NA

**Additional context**

**Comment by azlam-abdulsalam** [comment]
@sumanthreddybolledla  Thanks for raising this, Its been fixed in 2.7.0 and will be available as part of June 22 release.
