### ISSUE TITLE
npm publish logs missing

### ISSUE THREAD

**Issue by yippie** [dxatscale/sfpowerscripts#1082]
**Describe the bug**
When running `sfpowerscripts:orchestrator:publish`, if the internal `npm publish` command fails, its output is not shown or logged anywhere. This means it is very hard to troubleshoot WHY it failed to fix it. All the user knows is that it fails

**To Reproduce**

- Have a project setup for sfpowerscripts but with bad credentials in .npmrc.
- run quickbuild and then publish.
- The publish will fail (because of the bad credentials) but the only information available is `Command failed: npm publish --tag develop`. Log files in .sfpowerscipts/logs do not contain any additional information

**Expected behavior**
full output of npm publish to be logged in the log files

**Screenshots**

**Platform Details (please complete the following information):**
 - OS: macOS
 - Version [e.g. CLI Version  eg: 1.6.6] @dxatscale/sfpowerscripts 15.3.2
 - Salesforce CLI(sfdx cli) Version: sfdx-cli/7.159.0 darwin-arm64 node-v16.16.0

**Comment by azlam-abdulsalam** [comment]
Fixed in September 22
