### ISSUE TITLE
Env specific Org alias build failure

### ISSUE THREAD

**Issue by Janani-26** [dxatscale/sfpowerscripts#1083]
**Describe the bug**
When trying to create artifacts the job fails at quickbuild stage, for src-env-specific-alias-post with "Packages Failed To Build src-env-specific-alias-post" and "Package directory src-env-specific-alias-post is empty". but the folders inside alias post are not empty

**To Reproduce**
1. Create folders for different environments inside src-env-specific-alias-post 
2.  define the package in sfdx-project.json
3. trigger quickbuild stage using sfpowerscripts

**Expected behavior**
quickbuild and build jobs should be successful and artifact created and able to deploy to all orgs defined inside alias post

**Screenshots**

**Platform Details (please complete the following information):**
 image: ghcr.io/dxatscale/sfpowerscripts

**Additional context**

**Comment by azlam-abdulsalam** [comment]
@Janani-26 Can you confirm your .forceignore, whether you have ignored this folder. When using aliasified packages, you might need to use multiple ignore files per stages

https://docs.dxatscale.io/sfpowerscripts/orchestrator#handling-multiple-ignore-files

**Comment by Janani-26** [comment]
@azlam-abdulsalam , Thank you for the response, yes this folder was ignored in .forceignore. after removing it this worked. The bug can be closed.
