### ISSUE TITLE
sfdx sfpowerscripts:apextests:trigger throws error 

### ISSUE THREAD

**Issue by ppeers** [dxatscale/sfpowerscripts#1084]
**Describe the bug**
The following command:
sfdx sfpowerscripts:apextests:trigger -l RunAllTestsInPackage -n my-package-xxx -c --validatepackagecoverage

Throws this error in version 18.1.3 of sfpowerscripts:
Cannot read properties of undefined (reading 'packageVersionNumber')

**To Reproduce**

Package descriptor:
{
    "path": "xx/xx/my-package-xxx",
    "package": "my-package-xxx",
    "checkpointForPrepare": true,
    "versionNumber": "0.1.12.0",
    "type": "source",
    "reconcileProfiles": false
},

Run the command:
sfdx sfpowerscripts:apextests:trigger -l RunAllTestsInPackage -n my-package-xxx -c --validatepackagecoverage

**Expected behavior**
run unit tests and validate individual class code coverage for the package

**Screenshots**

**Platform Details (please complete the following information):**
 - Salesforce CLI(sfdx cli) Version: 7.159.0
 - sfpowerscripts version: 18.1.3

**Additional context**

**Comment by Chiqqn** [comment]
I confirm same issue.
