### ISSUE TITLE
Ability to specify the name of the release to set it in the Changelog file

### ISSUE THREAD

**Issue by ruslan-kurchenko** [dxatscale/sfpowerscripts#1102]
As a Release Manager,
I would like to set a release name,
So that delivery pipeline uses it in the Changelog file.

So, instead of the autoincremented counter, we would be able to reference releases to environments with actual Salesforce build versions (not just packages) and benefit from a detailed changelog file.

<img width="799" alt="Screenshot 2022-08-15 at 17 17 31" src="https://user-images.githubusercontent.com/29373749/184652966-a33eafec-334f-4198-beaa-a21dc009c4f7.png">

**Comment by vuha-acn** [comment]
Hi @ruslan-kurchenko. Can you provide more details and examples of what "Salesforce Build Versions" would look like and share a snippet of your current Release Definition file?  For the Salesforce Build Versions, are you referencing the Winter/Summer/Spring builds?

**Comment by ruslan-kurchenko** [comment]
Hello, @vuha-acn . I was confused with the logic that sets the name of the release. @azlam-abdulsalam helped me to understand it in Slack. I didn't realize that the "release" action assigns the release name based on the release-definition file.
Now, I can set the normal version name.

But the question is still open. I would like to be able to "override" the version name by directly passing the name of the release to the "release" command. In our use case, we start the Gitlab pipeline from a tag (version), and it would be perfect to pass this tag name to the command. At this point, I have to commit an updated release-definition file every time to pump the version. It is not that bad, but I think it would be a good enhancement.

**Comment by azlam-abdulsalam** [comment]
@ruslan-kurchenko  This can be done by using the upcoming release definition generator 
https://github.com/dxatscale/sfpowerscripts/pull/1106

The release definition will be mostly a static file
