### ISSUE TITLE
LATEST as a dependency MUST NOT scan the devhub, when an appropriate version is in the sfdx-project.json file.

### ISSUE THREAD

**Issue by docbill** [dxatscale/sfpowerscripts#1103]
**Describe the bug**
A dependency of VERSION #.LATEST means the LATEST version maybe used, not that it must be used.  In particular, the version number dependency is used by salesforce to block installing without the correct dependency.   e.g. If I list a dependency of 1.3.0.LATEST, then if I have version 1.2.9-3 of that package installed, I don't meet the dependency.  I must upgrade to at least 1.3.0-1 before I can install my depent package.

By scanning the repository though for the latest build, we are picking up developer builds that might not have any peer review, or testing.

**To Reproduce**
In our sfdx-project.json file we have:
```
        {
            "path": "./src/spark-integrations",
            "package": "spark-integrations",
            "versionName": "Version 0.1.0",
            "versionNumber": "0.1.0.0",
            "dependencies": [
                {
                    "package": "ApexFramework",
                    "versionNumber": "1.3.0.LATEST"
                }
            ]
        }
```
...
```
    "packageAliases": {
        "ApexFramework@1.2.1-1": "04t1U000007Lr9uQAC",
        "ApexFramework@1.2.1-2": "04t1U000007LrC5QAK",
        "ApexFramework@1.3.0-1": "04t1U000007LrCUQA0"
    }
```
In our main branch.   There is currently a pull request that has:
```
    "packageAliases": {
        "ApexFramework@1.2.1-1": "04t1U000007Lr9uQAC",
        "ApexFramework@1.2.1-2": "04t1U000007LrC5QAK",
        "ApexFramework@1.3.0-1": "04t1U000007LrCUQA0",
        "ApexFramework@1.3.0-2": "04t1U000007LrE6QAK"
    }
```

Our developer might at anytime build version 1.3.0-3.

**Expected behavior**
We expect when DX@Scale uses the main branch to build an org, it will use the LATEST version list in the file, which is 1.3.0-1.   We expect when DX@Scale builds the pull request branch it wil use 1.3.0-2.   We expect under no circumstances will DX@Scale use a build we did not list in the file, unless possible we listed NO builds that meet the depency criteria.

**Screenshots**

**Platform Details (please complete the following information):**
The is running on in a docker container in openshift.  I do not know which version or devops person has installed.

**Additional context**
This is an extremely critical security bug.  Because it means ANY developer with devhub access can inject code either deliberately, or accidently into sandboxes that has not been peer reviewed, or tested.  If they have the ability to promote a build, they may even be able inject the build into production orgs.

**Comment by docbill** [comment]
It probably helps to cover what I expect to happen in other scenarios, at it helps make sense of this.

Suppose I have:

```
        {
            "path": "./src/spark-integrations",
            "package": "spark-integrations",
            "versionName": "Version 0.1.0",
            "versionNumber": "0.1.0.0",
            "dependencies": [
                {
                    "package": "ApexFramework",
                    "versionNumber": "1.3.0-2"
                }
            ]
        }
```

Then I fully expect if I go to install spark-integrations in an org that already has 1.3.0-1 it will force me to upgrade to meet the dependency.  And if I have 1.3.0-3 I fully expect salesforce will make me downgrade to meet the depency.   The reason for specifying 1.3.0-LATEST is I don't want to force someone to either downgrade or upgrade to meet the depency.   It is quite possible I will build a 1.3.0-3, and QA will test it and found I introduced a bug.  In which case the version I would promote would be 1.3.0-2.   It would break the production push altogether if DX@Scale attempts to grab 1.3.0-3 after I promoted 1.3.0-2.   While for my other orgs, it is just installing a version with a known bug, rather than the one that passed the QA testing.

Now since salesforce only designed there framework to enforce depencies by rejecting versions not choosing versions, it is very difficult to determine from their documentatation how they really intended it to work.  But if they did intend it to arbitrarily grab the latest build from the devhub instead of parsing the sfdx-project.json, then they probably need to rethink their design as well.

**Comment by azlam-abdulsalam** [comment]
@docbill  Salesforce  will pick up the LATEST version of that series  of X.Y.Z (X.Y.Z.BuildNumber) from the DevHub while resolving the packages not from packageAliases.  LATEST is only applicable for build numbers and onus is on the developer to use semantic versioning appropriately, especially in production where  once promoted, the build number is fully ignored,

So if you intend to use a 1.2.9 version of a package,  you should not update the dependencies till your 1.3.0 is tested. 

We do not resolve package versions from the aliases provided, we resolve it using the DevHub, Here is a rundown on the logic how we resolve it

https://github.com/dxatscale/sfpowerscripts/blob/main/decision%20records/005-package-dependency-version-resolution.md

**Comment by azlam-abdulsalam** [comment]
After few more thought on this, I get your problem statement :),  but I believe from a risk perspective, its not that of an issue,
Consider the below scenarios in the order
- A Change introduced by a developer in a mono repository, only the apex-framework package, say its 1.3.0-3 (as it was set to 1.3.0-NEXT) , all other packages will not be built or validated.  QA tests and either decides to proceed this to a newer environment or drop it 
-  A dependent package spark-integrations is now updated, validation and build will pickup 1.3.0-3 (as it was mentioned to use whatever the LATEST of 1.3.0 series).  On the next environment, for spark-integrations to work it needs a version of package from 1.3.0 series. This has to be explicitly installed to sandboxes or production through release definition or manually,  Dev understands the error as 1.3.0 is not an approved package
- Dev reverts spark-integration and mark  the 1.2.9.LATEST as the dependency for spark-integrations, and build a new version which then gets tested and released to environments
- Meanwhile in the repository bugs are fixed on 1.3.0-LATEST of apex-frameworks, as long as they are backward compatible, validation on scratch orgs should not posess a challenge and you are validating the state of the repo at that point

I guess the issue here is while mono repo allows to iterate together on all packages at the same , versioning is a bit on the loose end (especially during validation and also having breaking changes),  i guess the way forward is , if the packages are stable, it needs to move out into its own repo or as a seperate project within the repo ( tooling support for it is on the way)

**Comment by rody** [comment]
Salesforce DX always resolve `.LATEST` to the latest version on the DevHub when creating a package version.

During the package version creation, Salesforce create an empty scratch org, resolve and install the latest dependencies, then compile and publish a new package version. The exact dependency used during the package version creation can be retrieved by SOQL, as described in: https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_unlocked_pkg_extract_dependency_info.htm. The only options offered are either a fixed version, or the latest one.

Long story short, the data on the DevHub is always the source of truth for sfdx.

In `sfdx-project.json` the `packageAliases` are just here as a convenient way to map a version string to a package Id or a package version Id. They are never used by sfdx to determine the `LATEST` or `NEXT` version during the builds.
DX@Scale is consistent with sfdx in the way it interprets the `LATEST` keyword.
 
**Back to your request, I see 2 options:**

1. In the scenario where the `LATEST` resolution is based on the latest version in `packageAliases`, you would have to prevent the auto-update of `packageAliases` (using `SFDX_AUTOUPDATE_DISABLE=true`) and add the alias manually or via a CI script. In that case, why not update the versions of the dependencies to the "validated/approved" one directly?

2. Another approach that you can try is the "branch" property in the package declarations. Note that the "branch" doesn't have to be linked to a GIT branch, it's much more a package release branch.

From the doc:
> version numbers increment within each branch, and not across branches. For example, you could have two or more beta package versions with the version number 1.3.0.1.

This means that the LATEST resolution will be per-branch. By using a different branch for "dev" and "testing" you could achieve the desired behavior.

I hope this helps.....

**Comment by rody** [comment]
Here is the relevant documentation about the "branch" property: https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_unlocked_pkg_use_branches.htm

**Comment by docbill** [comment]
I haven't seen the branch property before.  I'll have to take some time to digest if that really helps to solve the issue.

When one is building packages, you typically want to specify a minimum version that has the stable features your package needs.   In this particular example, I am the owner of the ApexFramework package and a contributor to the src/spark-integrations package.   I also have a RedHatFramework package I maintain which depends on ApexFramework.   I'm doing development for a particular user story and find I need a new feature for ApexFramework.   So I create a new branch in that project, build the package.  I notice I forgot to update the version from 1.2.1.  In this case I have delete permissions in the devhub, so I delete the bogus build.  If I didn't have that permission, others could pickup that untested build with the new feature.

I rebuild as a 1.3.0 version and now can add a dependency to code I'm working on that needs that feature.   That feature won't be fully tested until that story itself is fully tested.   The pull requests gets approved and is merged to our mani branch.  So now our sandboxes are free to receive 1.3.0-1.   I have a bit of down time waiting for my next merge request to get approved.   So I go back to work on the ApexFramework package.  While the build seems to be working perfectly, I am not happy about the PMD warnings, nor the fact I increased a 500 line class to a 600 line class to to add the new feature.   So I spend the afternoon refactoring and bulid as 1.3.0-2.   I don't expect any builds to pick that up yet, because I didn't list that build in the sfdx-project.json file yet.  But I go ahead and add it reference to it on the pull request I am working on, as QA still has not done any manual testing, so they might as well test the latest.

Now I get some more down time.  I notice many other classes have PMD warnings.  So I refactor and clean up all of those.   I explicitly cannot do a build though, because of this problem that my build will instantly go into our sit environment...

Now, you might say why don't I just specify an explicit version?  LIke 1.3.0-2?   Mainly because I don't want to force downgrades.   In the past I have for example had RedHatFramework dependant on 1.0 of ApexFramework, because that has all the features it requires.  I later had another package that required 1.1 of ApexFramework.   This did not cause an issue, because salesforce did not block the upgrades of RedHatFramework because I had a newer version of ApexFramework.   I assumed that is because the dependency was listed as 1.0.0.LATEST and 1.1 is newer than 1.0.

However, and salesforce API version later, and I had ApexFramework 1.2.1 installed.  When I went to update RedHatFramework it complained about the mismatching dependency.  I wasn't sure at the time if it was because Salesforce had revised the implementation for the dependency check to have to match the EXACT version (but not build), or if it was the  new tool chain blocking the install.

This later behavour is inconvient, but I can see how some might consider it desirable.  After all I might not have tested the RedHatFramework build against ApexFramework 1.2.1.   Salesforce dependency checks are not nearly as advanced as say maven.   But while it might be annoying to have to rebuild RedHatFramework to match the new version, it is not security issue.

It is however a security issue if builds are being pushed with other code, without some explicit indication that is OK.   Setting you the SFDX_AUTOUPDATE_DISABLE=true variable will not in the least resolve this issue.  Because in the majority of the time with Scale@DX it is not an upgrade, but a net new install.  Our scratch orgs are rebuild continously.  Every package is a first time install.  We at least plan on refreshing our other sandbox very regularly.  If the package is not already in production, then again it won't be an upgrade.

When you use the commandlines to create and package and a package version, this is the way vscode updates the file.  It will include the package alias as the package name without version number.  When you build a version it will build an alias with the package name # version number.  That is the format DX@Scale should expect.   There is no out of the box command to install dependencies.  A rather a reasonable developer will consult the sfdx-project.json file and select the appropriate version.  It turns out you don't even need devhub access to do this.  Someone at verion can take our unlocked package version in ApexFramework, and intall it in their org.  I do not encourage this, but salesforce allows it.   I actually have no idea if they are able to scan for package versions outside the ones listed in the the sfdx-project.json file we commit, but I would not expect them to do so.

A reasonable developer will consult the sfdx-project.json file for the versions to version aliases to install, and any reasonable person will expect a tool to default to the same actions as a reasonable developer.

**Comment by docbill** [comment]
It looks like the build cannot actually be specified in the dependency using the obvious syntax of `ApexFramework@1.3.0-2` :
```

81 ERROR running sfpowerkit:package:dependencies:install:  
82 MinorVersion=3 and PatchVersion=0-2 ORDER BY BuildNumber DESC, createddate
83                                ^
84 ERROR at Row:1:Column:236
85 unexpected token: -

```

**Comment by docbill** [comment]
Upon reviewing https://github.com/dxatscale/sfpowerscripts/blob/1c9f2e048cc0d5d160054d8d29ec9726fd8ae9a2/decision%20records/005-package-dependency-version-resolution.md

It looks like actually supporting version numbers correctly isn't even part of the flow.   If build is not the latest in the configured devhub, versioning simply won't work.  Which means if the package is build from a different devhub, no versioning supported.  If it is not considered acceptable to grab the latest build, versioning is not supported.

This explains why so many examples are populating the version id # instead of the package id # as the package name alias.  It is the only thing that works consistently if security is at all an issue.   Logically, it is about the same as when developers use maven and just specify to grab the latest each build from a repository.  That is fine, if you have very strict controls over what goes into the repository or if you don't need to meet any sort of regulator requirements, and you don't have significant security requirements.

**Comment by azlam-abdulsalam** [comment]
> It looks like the build cannot actually be specified in the dependency using the obvious syntax of `ApexFramework@1.3.0-2` :
> 
> ```
> 
> 81 ERROR running sfpowerkit:package:dependencies:install:  
> 82 MinorVersion=3 and PatchVersion=0-2 ORDER BY BuildNumber DESC, createddate
> 83                                ^
> 84 ERROR at Row:1:Column:236
> 85 unexpected token: -
> ```

You should be mentioning it as 1.3.0.2

**Comment by azlam-abdulsalam** [comment]
> Upon reviewing https://github.com/dxatscale/sfpowerscripts/blob/1c9f2e048cc0d5d160054d8d29ec9726fd8ae9a2/decision%20records/005-package-dependency-version-resolution.md
> 
> It looks like actually supporting version numbers correctly isn't even part of the flow. If build is not the latest in the configured devhub, versioning simply won't work. Which means if the package is build from a different devhub, no versioning supported. If it is not considered acceptable to grab the latest build, versioning is not supported.
> 
> This explains why so many examples are populating the version id # instead of the package id # as the package name alias. It is the only thing that works consistently if security is at all an issue. Logically, it is about the same as when developers use maven and just specify to grab the latest each build from a repository. That is fine, if you have very strict controls over what goes into the repository or if you don't need to meet any sort of regulator requirements, and you don't have significant security requirements.

If the package is from a different devhub, you need to explicitly mention the O4t id, in packageAliases. We treat that as an external dependency, just like a managed package

**Comment by azlam-abdulsalam** [comment]
Are you building your packages locally? I am not sure how build is receiving you new version unless you raise a PR and that was merged in. build only picks versions of packages that are validated and reachable from the current branch.

Now, I think there is a confusion around the concept of build and release,  or the way pipeline are setup.

Happy to discuss this on slack. 
https://launchpass.com/dxatscale

**Comment by azlam-abdulsalam** [comment]
Also FYI, while preparing scratch orgs, there are two options that you can use, either you can use the last validated version of the packages (whatever is published) or you can use deploy every package directory as it is. 

Now on the release side, you can control the package versions by explicitly mentioning in release definition.

This is a downside of a mono repo, the moment you merge a change, everyone using the same branch receives it, in their developer environments. This is why we split build and deployment pipelines

**Comment by azlam-abdulsalam** [comment]
I am closing this as there is no further activity on this one
