### ISSUE TITLE
Prepare command creates too many Scratch Orgs when using snapshot pool

### ISSUE THREAD

**Issue by domrycz** [dxatscale/sfpowerscripts#1105]
**Describe the bug**

When using sfpowerscripts:orchestrator:prepare command with pool config file which contains snapshotPool property, process creates as many scratch org as it sees in snapshot pool.
For example:
Pool A has maxAllocation set to 10 and snapshotPool set to pool B.
Prepare sees 0 scratch orgs in pool A and 13 in pool B.
It creates 13 scratch orgs in pool A (and leaves 0 in pool B).

**To Reproduce**

Use new snapshot property in pool config file.
Create a few scratch orgs in pool which is used as snapshot.
Then try to create less scratch orgs in pool which is based on snapshot one (and leave some of the scratch org still in snapshot pool).

**Expected behavior**
I want sfpowerscripts:orchestrator:prepare to look into given config file and keep the pool size at maximum level defined in maxAllocation property.

**Platform Details (please complete the following information):**
 - sfdx cli version: 7.159.0
 - powerscripts version: 18.1.3

**Comment by azlam-abdulsalam** [comment]
Hi @domrycz ,

Can you provide the two config files and the order of execution

**Comment by azlam-abdulsalam** [comment]
Based on discussion with @dieffrei, this scenario is not accomodated, currently snapshot pool will utilise all the scratch orgs provided in the input pool. It doesn't respect max allocation in the pool which consumes snapshot.

Current design only accomodate where parent pool and child pool has to have the exact number

**Comment by domrycz** [comment]
Cool, I was also talking with @dieffrei  so I think we are on the same page now. I have understood that I can have one base pool with managed packages installed and then use this pool as a "base" for a few different pools.

**Comment by azlam-abdulsalam** [comment]
We didn't think of this scenario;), but definitely looks like a valid use case. We will pick this up in September release
