### ISSUE TITLE
Plugin Documentation not available

### ISSUE THREAD

**Issue by nnamacha** [dxatscale/sfpowerscripts#1110]
The link https://docs.dxatscale.io/projects/sfpowerscripts is not working . Is the an alternative getting file not found

![image](https://user-images.githubusercontent.com/1133995/186333408-c3dcc7a3-103d-4533-a7d3-3ac3b869945a.png)

**Comment by vuha-acn** [comment]
Hi @nnamacha  - Can you please let me know the source page that you clicked on that link so I can confirm where it should go? We have been re-organizing our gitbook so some links have been updated.  Thank you for bringing it to our attention.

**Comment by nnamacha** [comment]
https://openbase.com/js/@dxatscale/sfpowerscripts.core/documentation

**Comment by vuha-acn** [comment]
Thanks. I'll check with @azlam-abdulsalam for access to update that site but for sfpowerscripts in general, you can just visit our main site at [https:/docs.dxatscale.io](https://docs.dxatscale.io/) or review the repo for [sfpowerscripts](https://github.com/dxatscale/sfpowerscripts).  You are more than welcome to join the [Slack](https://launchpass.com/dxatscale) channel as well for further questions.
