### ISSUE TITLE
Scratch Org Pool creation script failing "Unable to execute command .. Error: Can't find package id for dependency: 04txxxx"

### ISSUE THREAD

**Issue by eneag-sf** [dxatscale/sfpowerscripts#1113]
**Describe the bug**

NOTE: This issue started 2 days ago. No changes were done to the scripts/DevHub.
env-operations-prepare-ci-pool.yml & env-operations-prepare-dev-pool.yml scripts, which are auto-scheduled started to fail for the first time on 31.08.2022. The error shown is: 

`ERROR running sfpowerscripts:orchestrator:prepare:  Unable to execute command .. Error: Can't find package id for dependency: 04t4S000000HweFQAS`

**To Reproduce**

1. Clone https://github.com/dxatscale/dxatscale-template repo
2. Follow steps to connect to DevHub
3. Modify sfdx-project.json to add packages that need to be installed

```
{
  "packageDirectories": [
    {
      "path": "./force-app",
      "package": "DreamHouseORGD",
      "versionName": "Summer Release '23",
      "versionNumber": "55.0.0.NEXT",
      "default": true,
      "assignPermSetsPostDeployment": ["dreamhouse"]
    },
    {
      "path": "./src-env-specific",
      "package": "src-env-specific",
      "versionNumber": "1.0.0.0"
    },
    {
      "path": "./data",
      "package": "DataHD",
      "type": "data",
      "versionNumber": "1.5.0.0"
    },
    {
      "path": "./packages",
      "package": "Packages",
      "versionNumber": "1.0.0.0",
      "ignoreOnStage": ["prepare", "validate", "quickbuild", "build"],
      "dependencies": [
        {
          "package": "04t4S000000HweFQAS"
        },
        {
          "package": "04t58000000SGw3AAG"
        },
        {
          "package": "04t2w000009BbjoAAC"
        },
        {
          "package": "04t8b000001Eh4YAAS"
        },
        {
          "package": "04t5G000003rUvVQAU"
        },
        {
          "package": "04t5G000003rUvLQAU"
        }
      ]
    }
  ],
  "namespace": "",
  "sfdcLoginUrl": "https://login.salesforce.com",
  "sourceApiVersion": "54.0",
  "packageAliases": {
    "DreamHouseORGD": "0Ho5f000000TNHJCA4",
    "DreamHouseORGD@55.0.0-1": "04t5f000000elXBAAY"
  }
}
```

**Expected behavior**

The script should create the scratch orgs with the packages excatly as described in the json file.

**Platform Details (please complete the following information):**
 - OS: ubuntu
 - sfpowerscripts version: 19.4.1
 - Salesforce CLI version: 7.160.0
 - CI Platform: GitHub

**Comment by azlam-abdulsalam** [comment]
Please use packageAliases to mention this id's as a workaround
