### ISSUE TITLE
Refactor package installation implementation to use packaging lib

### ISSUE THREAD

**Issue by azlam-abdulsalam** [dxatscale/sfpowerscripts#1121]
Refactor the current implementation of installing packages that wrap around sfdx cli to use the underlying library directly.  The new library is available here https://github.com/forcedotcom/packaging

This will allow us to handle parallel packaging and errors much more cleanly and remove dependency on the CLI invocation

**Comment by vuha-acn** [comment]
@azlam-abdulsalam The CLI team says "⚠️ This module is under heavy development, please do not use in production." Are we going to schedule the refactoring release of the code when it's GA or just risk it and use it as it is?

**Comment by azlam-abdulsalam** [comment]
@vuha-acn When the current cli package:beta goes GA, we will switch to the lib
