### ISSUE TITLE
Add build/deploy errors to the .powerscripts/log path for sfpowerscripts:orchestrator:build and sfpowerscripts:orchestrator:release

### ISSUE THREAD

**Issue by Rocko1204** [dxatscale/sfpowerscripts#1132]
**Describe the bug**
The affected packages are currently output in the metric, but not the associated error message from the build or deploy job.

**To Reproduce**
Examples can be found in the metrixes or artifacts.

**Expected behavior**
The errors in the packages should also be available via metrix or your own log file.
Nice to Have: A json format would be desirable for a new file.

**Additional context**
Affected commands:
sfpowerscripts:orchestrator:build
sfpowerscripts:orchestrator:release

THX and Regards

**Comment by azlam-abdulsalam** [comment]
Thanks @Rocko1204 for raising this. This is definitely in the plans and will be addressed in a future release

**Comment by azlam-abdulsalam** [comment]
@Rocko1204  This is partially fixed, build command now emit individual logs of each package with finer details. More to follow

**Comment by azlam-abdulsalam** [comment]
This is being worked upon, there will be an additional outputs folder in .sfpowerscripts which will provide various outputs in markdown which can be integrated with CI systems

**Comment by azlam-abdulsalam** [comment]
Build Errors, Validation and Deployment errors are available in .sfpowerscripts/outputs folder from August23
