### ISSUE TITLE
Issue when publishing "big" artifacts

### ISSUE THREAD

**Issue by alanjaouen** [dxatscale/sfpowerscripts#1149]
**Describe the bug**
when an artifact is to big, execSync fail with ENOBUFS

**To Reproduce**
publish an artifact with a lot of files

**Expected behavior**
artifact should be uploaded

**Screenshots**
![image](https://user-images.githubusercontent.com/14994179/201987097-62bc19bf-1a95-48bd-9a85-433b2ce45b5e.png)

**Platform Details (please complete the following information):**
 - OS: Windows and linux (ubuntu)
 - Version : 19.7.3
 - Salesforce CLI(sfdx cli) Version:sfdx-cli/7.175.0 win32-x64 node-v18.3.0
 - CI Platform: local and github action

**Additional context**

same issue as #967, fixed on 028556644ac97a6e1b70c1d80dc7bc5e0787a74b and reintroduced on 11814c59ee29f6580b1cad2f6e3ddff3da3fe753

**Comment by azlam-abdulsalam** [comment]
@alanjaouen  Thanks for raising the PR, will be accommodated in November Release

**Comment by azlam-abdulsalam** [comment]
Fixed in Novemvber 2022 release
