### ISSUE TITLE
Orchestrator Validate should run apex tests on deploy not after

### ISSUE THREAD

**Issue by estebanefi** [dxatscale/sfpowerscripts#1160]
**Describe the bug**

When running `orchestrator:validate` as part of our validations we would like to be able to reuse the pooled scratch org when tests fail, but since tests are ran after the deployment it is not possible since.

**To Reproduce**

Deploy with a failing test, this will mark the pool for deletion

**Expected behavior**
Would expect the scratch org be returned to the pool, this would also open up being able to get code coverage with different formats (clover, cobertura)

**Platform Details (please complete the following information):**
 - OS: Ubuntu-Latest
 - Version [e.g. CLI Version  eg: 1.6.6] Using dx@scale docker Image
 - Salesforce CLI(sfdx cli) Version: Using dx@scale docker Image
 - CI Platform: Github Actions

**Additional context**
If it is preferred I open up a PR for this I will 😄

**Comment by azlam-abdulsalam** [comment]
Hello @estebanefi , tests are run after deployment to identify various coverage requirements, if we run test along with deploy, salesforce will validate for individual class coverage which is not the necessary pattern for unlocked packages where its overall coverage for a package.

There is a PR currently being worked on for retrying pools which might solve the reusability issue

https://github.com/dxatscale/sfpowerscripts/pull/1156

**Comment by azlam-abdulsalam** [comment]
I am closing this ticket due to non activity and will be resolved in the future
