### ISSUE TITLE
GitLab NPM Scope failures in Orchestration Jobs for Latest November 22-1 Release

### ISSUE THREAD

**Issue by vuha-acn** [dxatscale/sfpowerscripts#1168]
**Describe the bug**
Pipelines for GitLab broken with latest November 22 - 1 release causing NPM artifacts to not be detected.

**To Reproduce**

1. Update Package
2. Run Pipeline for Validate/Build
3. Error in pipeline - see sample error message below

**Expected behavior**
NPM Scope, Build/Publish jobs work as normal w/o appending additional "@" sign to invalidate the artifact repository usage.

**Screenshots**

npm ERR! Invalid name: "@@npm_scope/core-crm_sfpowerscripts_artifact"
[79](https://gitlab.com/organization/project/-/jobs/3439921922#L79)npm ERR! A complete log of this run can be found in:
[80](https://gitlab.com/organization/project/-/jobs/3439921922#L80)npm ERR!     /root/.npm/_logs/2022-12-07T17_24_15_684Z-debug-0.log

**Platform Details (please complete the following information):**
 - OS: Amazon Linux
 - Version [e.g. CLI Version  eg: 1.6.6] - Latest
 - Salesforce CLI(sfdx cli) Version: Latest
 - CI Platform: GitLab

**Additional context**

**Comment by azlam-abdulsalam** [comment]
@vuha-acn  Thanks, this is fixed in

https://github.com/dxatscale/sfpowerscripts/commit/4665c1d4ac4d81ee081c7f14ca0de4f67fbc25af
and is scheduled for a hotfix
