### ISSUE TITLE
sfpowerscripts:orchestrator:quickbuild not honoring config path

### ISSUE THREAD

**Issue by yippie** [dxatscale/sfpowerscripts#1176]
**Describe the bug**
All package builds are failing with `ENOENT: no such file or directory, open 'config/project-scratch-def.json'`

It is true that 'config/project-scratch-def.json' doesn't exist in my project. However, we are specifying `-f config/orgs/project-scratch-def.json` and that same path is in the sfdx-project.json file for each package as well. 

**To Reproduce**
1. Have scratch-def files configured in a non-default location
2. run `sfdx sfpowerscripts:orchestrator:quickbuild -v devhub --diffcheck --buildnumber ${GITHUB_RUN_ID} --branch ${GITHUB_REF#refs/heads/} -f config/orgs/project-scratch-def.json`

**Expected behavior**
Build to succeed

**Platform Details (please complete the following information):**
Github Actions
runs-on: ubuntu-latest
container:
   image: ghcr.io/dxatscale/sfpowerscripts:latest
sfpowerscripts  -- The DX@Scale CI/CD Orchestrator -Version:20.2.6 -Release:November 22

**Additional context**

**Comment by azlam-abdulsalam** [comment]
@yippie did you notice this only with November 22?

**Comment by yippie** [comment]
I had a build Succeed on Dec 3 (which was running September 22 release) and then the next build, yesterday, failed. So yes, it seems to be caused by the November 22 release
