### ISSUE TITLE
Quickbuild command is not respecting .forceIgnore specific file

### ISSUE THREAD

**Issue by dieffrei** [dxatscale/sfpowerscripts#1178]
**Describe the bug**
Quick build command is not detecting changes on packages that are using **aliasify** flag as true.
As workaround we have to bump the packages.

**To Reproduce**
1. Install sfpowerscript version: @dxatscale/sfpowerscripts 20.2.11
2. Create a package aliasified
3. Add entry of the package in .forceIgnore 
4. Create an specific .forceIgnore for quick build ("quickbuild": "forceignores/.quickbuild-ignore"), and configure in your sfdx-project.json
5. Change any content on the package, (do not change the package descriptor)
6. Run sfdx sfpowerscripts:orchestrator:quickbuild -v devhub --branch branch --buildnumber 1299393 --diffcheck --configfilepath config/package-org-def.json --loglevel trace
7. No changes will be detected
8. Now remove the entry from  default .forceIgnore (not quick build specific one)
9. Run the command of quick build again, and the changes would be detected.

**Important:**: Bug only presented on the latest version, I've downgraded to 19.7.3, and change detection is working fine

**Expected behavior**
Detect changes on aliasified packages, and respect command specific .forceIgnore files

**Screenshots**

**Platform Details (please complete the following information):**
 - OS: Linux
 - Version [e.g. CLI Version  eg: 1.6.6] 20.2.11
 - Salesforce CLI(sfdx cli) Version:7.173.0
 - CI Platform: Gitlab

**Additional context**

**Comment by azlam-abdulsalam** [comment]
Fixed in Jan 2023 release
