### ISSUE TITLE
releasedefinition:generate does not generate "promotePackagesBeforeDeploymentToOrg" attributes correctly to Release Definition File

### ISSUE THREAD

**Issue by vuha-acn** [dxatscale/sfpowerscripts#1180]
**Describe the bug**
sfdx sfpowerscripts:releasedefinition:generate does not generate the following Release Definition Property "promotePackagesBeforeDeploymentToOrg" correctly when specified in the release-config file.

**To Reproduce**

1. Create release-config file with the following:
```
releasedefinitionProperties:
  promotePackagesBeforeDeploymentToOrg: "SIT"
```
2. Execute sfdx sfpowerscripts:releasedefinition:generate command

**Expected behavior**
Release definition file with the following property created:

`promotePackagesBeforeDeploymentToOrg: "SIT"`

**Screenshots**

**Platform Details (please complete the following information):**
 - OS: MacOS Monterey - 12.6.2 
 - Version [e.g. CLI Version  eg: 1.6.6] - @dxatscale/sfpowerscripts 20.4.3
 - Salesforce CLI(sfdx cli) Version: sfdx-cli/7.181.1 darwin-x64 node-v18.7.0
 - CI Platform: GitLab

**Additional context**

[Automatic Generation of Release Definition](https://github.com/dxatscale/sfpowerscripts/blob/main/decision%20records/release/006-release-defn-generator.md)

**Comment by azlam-abdulsalam** [comment]
Fixed in January 23
