### ISSUE TITLE
Make :publish command to push only packages version tags

### ISSUE THREAD

**Issue by ruslan-kurchenko** [dxatscale/sfpowerscripts#1183]
**Describe the bug**
In our build process, we use floating tags to specify the latest successful build commit. In some cases, we merge multiple release branches at a time. As a result, multiple publish jobs are executed, and they push all tags from the repo (if I understand it correctly). As we have floating tags, it might happen that one push tried to push a floating one into the old position (commit), resulting in job failure. 

**To Reproduce**
There is no standard way to reproduce it but you would emulate it.
- Create a tag on some old commit of the trunk. "lastest-successful-build-main" for example
- Trigger a build process
- Wait till the build job started
- Quickly re-create the tag with the same name on the last commit and push it wish force param to override the position
- Publish commit should fail (see screenshot)

**Expected behavior**
- Publish command should not publish tags which are not relevant to packages' versions

**Screenshots**
<img width="1227" alt="Screenshot 2022-12-19 at 14 00 15" src="https://user-images.githubusercontent.com/29373749/208880153-342c9218-bac1-4a90-b56e-5b23a872f286.png">

**Platform Details (please complete the following information):**
 - OS: not relevant
 - Version not relevant
 - Salesforce CLI(sfdx cli) Version: not relevant
 - CI Platform: GitLab

**Comment by azlam-abdulsalam** [comment]
Added a new enhancment  in January23  that resolves this issue
