### ISSUE TITLE
Issue occured while building the salesforce unlock package - error code: 1479842573-694(-852365351)

### ISSUE THREAD

**Issue by amit-ranganekar** [dxatscale/sfpowerscripts#1198]
**Describe the bug**
We are trying to build the salesforce unlock packages through salesforce sfpowerscript command and are getting below error. It was working fine before but suddenly we are observing this issue.

**To Reproduce**
We can execute the below sfpowerscript command to build unlock packages.

**Expected behavior**
Package should be built

**Platform Details (please complete the following information):**
 - OS: We are using docker image salesforce/salesforcedx:latest-slim
 - Version [e.g. CLI Version  eg: 1.6.6]: 
 - Salesforce CLI(sfdx cli) Version: `salesforce/salesforcedx:latest-slim`
 - CI Platform: GitLab pipeline

**Comment by azlam-abdulsalam** [comment]
@amit-ranganekar  This is an unkown error with at salesforce end ( We ca this GACK ID.) Please reach out to salesforce support with the error and they can help you fix the issue.
