### ISSUE TITLE
orchestrator:build job removes too many packages from queue after single failure 

### ISSUE THREAD

**Issue by con242** [dxatscale/sfpowerscripts#1199]
**Describe the bug**
When a package is failing during build job, it removes all childs from queue. Unfortunately it not only removes its own childs, but also others in queue. 

**To Reproduce**
Following Setup: 

Package1
- no deps 

Package2
- dep on package1

Package3
- no deps 

Package4
- dep on package3

- Build jobs starts: Package(s) currently processed: Package1, Package3. Packages in queue: Package2, Package4. 
- Package 1 fails: "Error XYZ. Removing childs from queue" 
- Package3 successfully builds: "Version X.Y.Z successfully created" 
- Job ends with message: 1 package created. 1 Package failed: package2. 

-> Package 4 disappeared!

**Expected behavior**
If a package fails only child packages of that package must be removed from queue, not child packages of other packages. 

**Platform Details (please complete the following information):**
 - Version 20.2.11
 - Salesforce CLI(sfdx cli) Version: 7.179.0
 - CI Platform: Gitlab CI

**Comment by azlam-abdulsalam** [comment]
Looks like this happens for any errors in the first parent nodes, investigating..
