### ISSUE TITLE
SFDX Update to 7.180 from 7.179 

### ISSUE THREAD

**Issue by estebanefi** [dxatscale/sfpowerscripts#1201]
**Describe the bug**

Would be great to have this version update!
https://github.com/forcedotcom/cli/issues/1713

**To Reproduce**

When retrieving deploy report I will sometimes get this error

`sfdx force:source:deploy:report`

**Expected behavior**

This error should not happen

**Screenshots**

**Platform Details (please complete the following information):**
 - OS: Linux
 - Version: docker image version
 - Salesforce CLI(sfdx cli) Version: 7.179 
 - CI Platform: Github Actions

**Comment by azlam-abdulsalam** [comment]
@estebanefi  sfdx cli updates are handled as part of monthly updates. 

If you are running locally, please feel free to update the cli to your version of choice. we no longer have a dependency on a specific version
