### ISSUE TITLE
Unpackaged metadata not provided to sfdx build in newest sfpowerscripts version

### ISSUE THREAD

**Issue by petter-eikeland** [dxatscale/sfpowerscripts#1202]
**Describe the bug**
Newest sfpowerscripts version gives the following error upon Orchestrator Build: `Un-packaged metadata directory unpackagedMetadata was specified but does not exist.` I see that support of this option was added as a result of [this issue](https://github.com/dxatscale/sfpowerscripts/issues/958).

**To Reproduce**
1. Create an Unlocked Package, **test-package**, under the **src** directory and add it to the sfdx-project.json and include an Account field, testField__c
1. Add another directory, src/unpackaged, and add another Account field, testField2__c
1. Add the `unpackagedMetadata` option as below:
```
"unpackagedMetadata": {
    "path":"src/unpackaged"
},
```
4. Create a new version of **test-package** using `sfdx sfpowerscripts:orchestrator:build -v devhub --branch master --diffcheck --buildnumber $(Build.BuildId) -f config/project-scratch-def.json` & the latest version of sfpowerscripts using `container: ghcr.io/dxatscale/sfpowerscripts:latest`

**Expected behavior**
A new package version is successfully created 

**Actual behavior**
sfdx throws the following error:  `Un-packaged metadata directory unpackagedMetadata was specified but does not exist.`

**Screenshots**
![Screenshot 2023-01-24 at 10 11 33](https://user-images.githubusercontent.com/97173615/214252783-0d01d447-7e18-490b-81a1-8af207d48a2c.png)

**Platform Details (please complete the following information):**
- OS: Linux
- Version: Ubuntu Latest
- Salesforce CLI(sfdx cli) Version:
  - sfpowerscripts: latest (20.2.11)
  - sfdx: 7.179.0
- CI Platform: Azure DevOps

**Additional context**
If downgrading to sfpowerscripts version: 19.7.3 using `container: ghcr.io/dxatscale/sfpowerscripts:19.7.3-3140166080` then the orchestrator:build works successfully as expected

**Comment by azlam-abdulsalam** [comment]
Thanks @petter-eikeland for investigating this. Will address in Jan 23 release

**Comment by azlam-abdulsalam** [comment]
ixed in Jan23
