### ISSUE TITLE
feat: Always use the newest validation scratch org during Validate

### ISSUE THREAD

**Issue by petter-eikeland** [dxatscale/sfpowerscripts#1228]
**Describe the feature enhancement**
We are using the thorough mode in our Validate Process. At the start of a typical day the first PRs are fast as only the newest changes are validated. However, throughout the day the PR validation gets slower and slower. This is because the validation org was created at midnight and tests the same functionality that was merged to master and built successfully earlier the same day. 

We are Replenishing the Validate Pool at midnight, 10, 12 and 14. If Validate always used the newest scratch org in the pool, it would mitigate some of this slowdown as it would already contain the latest changes from the same day.

**Comment by azlam-abdulsalam** [comment]
@petter-eikeland thats a smart idea,  so instead of the current round robin, sort by updated date.

We will still need to figure out a particular use case where we feed in 'empty pools' one without installAll, as the last resort.

Also, curious why haven't you tried the fast feedback mode?

**Comment by azlam-abdulsalam** [comment]
@zhebinliu  @vuha-acn thoughts?

**Comment by vuha-acn** [comment]
Using the latest created scratch org would make sense for people that are replenishing it more frequently.  My only question is is there a reason to not also delete the old ones first prior to replenishing and filling up more scratch orgs to reduce the footprint?

**Comment by petter-eikeland** [comment]
@azlam-abdulsalam Good question. Honestly, I haven't had the time to check it out yet. We used thorough in previous projects and is quite satisfied it. But I'll check it out when I have the time. 

@vuha-acn Hmm, I though about it. The reason why I didn't delete them prior to replenishing is that it takes ≈ 1 hour to replenish the first batch of scratch orgs (brownfield project with many managed, unmanaged & unlocked dependencies). So that would block the validation process for that hour. In addition, the replenish job can fail if previous builds caused upstream errors in top-level packages (e.g. deleting a field which is still referenced in src-access-mgmt)

**Comment by pogilvieCB** [comment]
Could we keep the orchestrator cache replacement policy as FIFO by default?   I'd like to avoid needing big purges and cleaning operations clean out stale orgs.   At the fruit stand the grocer puts the oldest fruit on top.

**Comment by pogilvieCB** [comment]
I think it's fine to add an option.

**Comment by petter-eikeland** [comment]
@pogilvieCB I would present the analogy in a different way. The fruit the grocer puts on top is the product the grocer is selling. The scratch org is not the product that we are selling, the commits flowing to PROD are our products. The scratch orgs in our validation pipelines are merely means to validate our products. Thus, if keeping the orchestrator FIFO then you in effect validate old changes unecessarily. The goal should be to get the commits to PROD as fast as possible. 

To put in terms of your analogy, the validation pipeline would be a fruit inspector inspecting the fruits being placed on the stand. He first inspects the apple and approves it. Then when an orange is placed on top, the fruit inspector needs to inspect the apple he already approved earlier in addition to the orange.

To avoid stale orgs, I recommend using [the scheduled pool cleaner template pipelines provided by DX@Scale](https://github.com/dxatscale/dxatscale-template). Thus, you delete all remaining orgs in the pool before you replenish the pool at e.g. midnight to ensure you have up-to-date scratch orgs.
