### ISSUE TITLE
feat: filter deploy command based on a release definition

### ISSUE THREAD

**Issue by alanjaouen** [dxatscale/sfpowerscripts#1232]
**Describe the feature enhancement**
Filter deployed package on `sfpowerscripts:orchestrator:deploy` based on a release definition

**Background**
I'm using multiple targeted production with different needs (aka deploying some common package and some specific one).
To achieve that, I've wrote two release generator definition, on per targeted production.
Based on theses file, I can:
- create multiple Scratchorg pools
- filter deployed artifacts on `validate` with mode `thorough-release-config`
- filter deployed artifacts on `release` by generating release definition from release generator definition

I tried to do the same kind of filter for `deploy` operation, but I didn't see any kind of filter like the `thorough-release-config` mode for prepare, and I think it will be a good addition

**Comment by azlam-abdulsalam** [comment]
We have been thinking for a while to move deploy out of orchestrator topic and get release to work with a given set of artifacts as well , this will remove a lot of confusion too and make docs simple.

What do you think, will it suit your usecase?

**Comment by alanjaouen** [comment]
Hi @azlam-abdulsalam,
I think it can fit my use case, but depends how the implementation is done:
To give you more context, I use deploy operation during integration (CI) with steps
```mermaid
flowchart LR
    A[quickbuild]
    B[deploy to integration 1]
    C[deploy to integration 2]
    D[build]
    E[publish]

    A --> B --> D
    A --> C --> D
    D --> E
```
if the new `release` just deploy all artifacts that are in actifacts (quickbuilded), it will be the same for me (or I will have to remove manually some artifacts on the directory)
like
```mermaid
flowchart LR
    A[quickbuild]
    B1[custom script filtering articacts\naccording to integration1 release definition]
    B[new release to integration 1]
    C1[custom script filtering articacts\naccording to integration2 release definition]
    C[new release to integration 2]
    D[build]
    E[publish]

    A --> B1 --> B --> D
    A --> C1 --> C --> D
    D --> E
```
A more convenient way (for me) to do it will be to pass the release definition generation
```mermaid
flowchart LR
    A[quickbuild]
    B["new release to integration 1 with --realasedef=#quot;path to integration1 releasedef#quot;"]
    C["new release to integration 2 with --realasedef=#quot;path to integration2 releasedef#quot;"]
    D[build]
    E[publish]

    A --> B --> D
    A --> C --> D
    D --> E
```
or an intermediate way like
```mermaid
flowchart LR
    A[quickbuild]
    B1[Generate release definition according\nto integration1 release definition]
    B[new release to integration 1 with generated realease]
    C1[Generate release definition according\nto integration2 release definition]
    C[new release to integration 2 with generated realease]
    D[build]
    E[publish]

    A --> B1 --> B --> D
    A --> C1 --> C --> D
    D --> E
```

**Comment by azlam-abdulsalam** [comment]
@alanjaouen  thanks for the detailed notes, I   will schedule this for march release,  I am  also looking at an option where we could use release config file (as opposed to release defn) for deploy command or use release command with release config directly.

**Comment by azlam-abdulsalam** [comment]
@alanjaouen  added an option to deploy flag in the current 20.28.0 , feedbacks welcome
