### ISSUE TITLE
Add the ability to increment retry counts 

### ISSUE THREAD

**Issue by Cherie-she** [dxatscale/sfpowerscripts#1233]
**Description**
Currently, we are facing SOs installation issues,  the error messages is : Cannot update or delete a picklist while a picklist background job is being executed. The current command automatically retries installation of a package on a failed deployment (when "retryOnFailure"is set to true) which normally solves the problem. However, it seems in this scenario more default retry count is needed.

Therefore, I would like to request a new feature that allows users to specify the number of retries for failed deployments when using the sfpowerscript command. This would enable users to increase the retry count beyond the default 2 attempts and would help to avoid package installation issues we currently having with our SOs.

**Proposed solution** 
Add a new parameter to the sfpowerscript command that allows users to specify the number of retries for failed deployments. For example, a new parameter called "retryCount" could be added in the config files, which accepts an integer value indicating the number of retries to attempt.

**Screenshots**
<img width="769" alt="image" src="https://user-images.githubusercontent.com/107973911/218916965-cff59523-8b33-481b-b9c5-a3baca392d1d.png">

**Platform Details**
Operating System: Windows 10
sfpowerscript version: 20.20.0
Salesforce API version: 53.0

This feature would greatly improve the deployment process and make our validation process faster. Thank you for your consideration.

**Comment by azlam-abdulsalam** [comment]
@Cherie-she  Scheduled for Feb 23

**Comment by azlam-abdulsalam** [comment]
Added a maxRetryCount  to pool config that will help with similar issues

https://github.com/dxatscale/sfpowerscripts/blob/a5e42d63926b0ac6f888e81038e227edb5b26e63/packages/core/resources/pooldefinition.schema.json#L95
