### ISSUE TITLE
SFDX Org List recognizes fetched scratch orgs as non-scratch orgs

### ISSUE THREAD

**Issue by petter-eikeland** [dxatscale/sfpowerscripts#1246]
**Describe the bug**
Fetched scratch orgs are recognized as orgs instead of scratch orgs when running sfdx org list. See https://dxatscale.slack.com/archives/CN9N54GF5/p1677010652929829 and https://github.com/forcedotcom/cli/issues/1941 for more information

**To Reproduce**
Update to newest sfdx version. Fetch a scratch org and run sfdx org list. Scratch org will be listed as org instead of scratch org.

**Expected behavior**
Scratch org is listed as scratch org

**Screenshots**
![image](https://user-images.githubusercontent.com/97173615/220455333-7d0b8f84-a857-4d92-b851-746d84207762.png)

**Platform Details (please complete the following information):**
 - OS: Mac
 - Version: 20.20.3
 - Salesforce CLI(sfdx cli) Version: 7.189.1
 - CI Platform: Azure DevOps

**Additional context**
According to one user, Windows users are also experiencing issues with sfdx source commands, possibly related to this.

**Comment by azlam-abdulsalam** [comment]
More info here https://github.com/forcedotcom/cli/issues/1941

**Comment by petter-eikeland** [comment]
sfdx v7.194.1 contains a fix for this!  https://github.com/forcedotcom/cli/issues/1941#issuecomment-1481645643

**Comment by azlam-abdulsalam** [comment]
@petter-eikeland  Thanks..  can we close this ?

**Comment by petter-eikeland** [comment]
Yeah, the bug is still present when using sfpowerscripts fetch, but not when authenticating with sfdx. Probably until the dependencies are updated to this sfdx version? So I quess we can close this as it will resolve itself soon

**Comment by azlam-abdulsalam** [comment]
I  will close this along with the update to the dependencies. Thanks @petter-eikeland  for the confirmation

**Comment by azlam-abdulsalam** [comment]
@petter-eikeland  there was a fix to the code as well.  I have patched this in 20.3.2
