### ISSUE TITLE
Unable to install this extension from Azure DevOps  server

### ISSUE THREAD

**Issue by rohiton31dec** [dxatscale/sfpowerscripts#125]
I am unable to download this extension and use it. Keep getting "Error occurred when downloading the extension, please try again later" and on the other side another error says "Permission section could not be loaded". I am on Azure DevOps server and I think I do have the permission because I was able to install a different extension. Are there any special privileges required to install this extension?
<img width="1422" alt="Screen Shot 2020-08-17 at 9 36 23 AM" src="https://user-images.githubusercontent.com/6539066/90408559-9a1efa80-e06d-11ea-8778-cfc59d33d6e5.png">

**Comment by azlam-abdulsalam** [comment]
Not sure, @rohiton31dec  can you raise an issue with Microsoft Support!
The scopes/permissions that we need are 
        "vso.build_execute",
        "vso.release_manage",
        "vso.serviceendpoint_manage"

**Comment by Caitlyn-Mills** [comment]
Hi @rohiton31dec unfortunately we are unable to recreate the error on our end. Could you please ensure you have the correct permission levels to install the extension in your org.

**Comment by azlam-abdulsalam** [comment]
@rohiton31dec  Any updates?

**Comment by azlam-abdulsalam** [comment]
Closing this as no feedback received
