### ISSUE TITLE
Validation of sfdx-project.json blocks other extensions

### ISSUE THREAD

**Issue by Schuchie** [dxatscale/sfpowerscripts#1256]
**Describe the bug**
The validation of sfpowerscripts blocks the extension from the sfdx-project.json. Sfpowerscripts should only validate json ranges that are managed by Sfpowerscript. Otherwise third party extensions will be blocked or prevented from adding properties e.g. to the packages.

**To Reproduce**
For example add a property to the one of the package, which is not included/supported by sfpowerscripts, but in another package:
```
{
  "packageDirectories": [
    {
      "path": "./src-translation",
      "package": "translation",
      "versionNumber": "1.0.0.0",
      "testProperty": ["Test","Test123"],
      "dependencies": []
    }
  ],
  "namespace": "",
  "sfdcLoginUrl": "https://login.salesforce.com",
  "sourceApiVersion": "57.0",
  "packageAliases": {}
}
```

**Expected behavior**
No error happens on running the command `sfdx sfpowerscripts:orchestrator:validate`

**Screenshots/Log**
```
ERROR running sfpowerscripts:orchestrator:validate:  The sfdx-project.json is invalid, Please fix the following errors

1: /packageDirectories/4: must NOT have additional properties {
    "additionalProperty": "testProperty"
}
Error: Process completed with exit code 1.
```

**Platform Details (please complete the following information):**
 - OS: Ubuntu
 - Version sfpowerscripts: sfpowerkit  -- The DX@Scale Developer Toolkit - Version:5.0.0 - Release:August 22
 - Salesforce CLI(sfdx cli) Version: 7.186.2
 - CI Platform: GitHub Actions

**Additional context**

For features that are currently ported from sfpowerkit to sfpowerscripts and are not yet supported, a validation should be made explicitly on the respective properties (e.g. replacements).
<img width="471" alt="image" src="https://user-images.githubusercontent.com/18148112/222444834-fb6e88ab-56c7-449a-a627-a461b94e8047.png">

Reason for blocking: `sfpowerscripts/packages/sfpowerscripts-cli/resources/schemas/sfdx-project.schema.json:33`

One way to implement the validation would be with the following:
```
//sfpowerscripts/packages/sfpowerscripts-cli/resources/schemas/sfdx-project.schema.json:34
                "properties": {
                    "replacements": {
                        "not": {}
                    },
                    "ancestorId": {
                        "$ref": "#/definitions/packageDirectory.ancestorId"
                    },
```
would result into the following error:
<img width="839" alt="image" src="https://user-images.githubusercontent.com/18148112/222474712-1dd5bfa5-4663-46a8-bc3e-de19a77dcd78.png">

**Comment by azlam-abdulsalam** [comment]
The validation is removed in February 23 release, future work will be scheduled for validation of properties used by sfpowerscripts or disabling features  not suppoerted
