### ISSUE TITLE
Add support for release config to build command 

### ISSUE THREAD

**Issue by azlam-abdulsalam** [dxatscale/sfpowerscripts#1265]
Build command in the current iteration builds all changed packages or all the packages in the current repository. It would be a worthwhile option to add support of release config to build command to filter packages and only build the changed ones as per the config.  This would  help reduce build times and  allows for more safer builds when used in scenarios such as fix on a release branch

**Comment by con242** [comment]
That would be great! 
Currently we achieve the same running a script that receives a package name and then sets all other sfdx-project.json to "ignoreOnStage": ["build"] and commit it to the hotfix branch. 

using a config file to list the package that can be optionally passed in the build job seems like a cool idea.
