### ISSUE TITLE
sfdx sfpowerscripts:dependency:install finds the latest version across different branches

### ISSUE THREAD

**Issue by johnforeland** [dxatscale/sfpowerscripts#1270]
**Describe the bug**
I'm using `sfdx sfpowerscripts:dependency:install` to install dependencies from sfdx-project.json. I have a package with a dependency to another package (sf-platform-oppslag, see pictures of where this is relevant), which is set to version `1.1.0.LATEST` in sfdx-project.json.

Previously, using sfpowerkit, it would correctly find version `1.1.0.22` (beta 22, which is the latest release for version 1.1.0 in the default branch. See picture).

![image](https://user-images.githubusercontent.com/6638390/225307376-bc6ebf35-a8e7-452c-ada8-4bf281e00b71.png)

But after changing to sfpowerscripts, the scripts finds version `1.1.0.40` (beta 40, which is from another branch, see pictures below). But 1.1.0.40 is neither the latest release for 1.1.0 in any branches, nor is it correct to assume that version should be used.

![image](https://user-images.githubusercontent.com/6638390/225307768-7c99dd61-375c-4fce-bfdb-9c3069ad6f26.png)
![image](https://user-images.githubusercontent.com/6638390/225307793-fb28cac8-d426-4ab5-a073-004eec6b7254.png)

Is this by design? And would it be possible to decide which branch to choose from when running sfdx sfpowerscripts:dependency:install?

**To Reproduce**

1. Have package A
    - Create package version without any branch, e.g. 1.1.0 beta 1
    - Create package version with a branch, e.g., `dev`, with version 1.1.0 beta 1
    - Create another package version for branch `dev`, but version 1.1.0 beta 2
4. Have Package B (which is also a separate repo)
    - Update sfdx-porject.json to have a dependency to Package A, with version `1.1.0.LATEST`
6. Using `sfdx sfpowerscripts:dependency:install` on Package B will result in finding 1.1.0.2

**Expected behavior**
Expected results would be that `sfdx sfpowerscripts:dependency:install` finds 1.1.0.1, as the default branch. Or at least the possibility to specify branch when using `sfdx sfpowerscripts:dependency:install`.

**Platform Details (please complete the following information):**
 - OS: macOS and Linux
 - Version [e.g. CLI Version  eg: 1.6.6]: 20.26.3
 - Salesforce CLI(sfdx cli) Version: 7.190.2
 - CI Platform: GitHub Actions

**Comment by azlam-abdulsalam** [comment]
Fixed in #1322
