### ISSUE TITLE
Dependency Install no longer working

### ISSUE THREAD

**Issue by kylethornton** [dxatscale/sfpowerscripts#1271]
**Describe the bug**
The `sfdx sfpowerscripts dependency install` command is throwing an error `TypeError: Cannot read properties of undefined (reading 'prototype')`

**To Reproduce**
- Update to latest version of sfpowerscripts
- execute `sfdx sfpowerscripts dependency install`
- See error

**Expected behavior**
Function should execute

**Screenshots**
![image](https://user-images.githubusercontent.com/757939/225352154-b913df2d-4d41-4cb5-801d-5d7a681ce240.png)

**Platform Details (please complete the following information):**
 - OS: Mac Ventura 13.2.1
 - Version [e.g. CLI Version  eg: 1.6.6] : 20.26.3
 - Salesforce CLI(sfdx cli) Version: 7.191.1
 - CI Platform: local machine

**Additional context**
Add any other context about the problem here. N.A

**Comment by azlam-abdulsalam** [comment]
@kylethornton  Can you uninstall the plugin and try again?

**Comment by kylethornton** [comment]
Same result @azlam-abdulsalam 

<img width="973" alt="image" src="https://user-images.githubusercontent.com/757939/225787418-26d7d2f3-8476-4d4f-9351-fe906e9cc505.png">

**Comment by kylethornton** [comment]
@azlam-abdulsalam I removed sfpowerkit, got an error it was needed, reinstalled and now everything seems to be working.
