### ISSUE TITLE
[FEATURE][AZURE] Add the ability to deploy a zip file instead of a directory 

### ISSUE THREAD

**Issue by JoelBrenstrum** [dxatscale/sfpowerscripts#128]
We currently run our deploys from azure based on a zip file. It would be really nice if we could use sfpowerscripts (DeploySourceToOrgTask) to manage our deployments but its just missing this one feature. 
`sfdx force:mdapi:deploy` supports a `-f` option for a zip file.

``` 
DeploySourceToOrgImpl

      //directory
      command += ` -d ${this.mdapiDir}`;

**Comment by JoelBrenstrum** [comment]
I have made the change locally but am struggling to build it on a windows box.

**Comment by azlam-abdulsalam** [comment]
@JoelBrenstrum  Can you shed up some more light on how the zip file is being generated and whats the idea behind it. Are you zipping it during a build stage?

**Comment by JoelBrenstrum** [comment]
Yup. We're making the zip a build artifact and picking it up further in the release pipeline. 
https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/file_based_zip_file.htm

Zip contents
![image](https://user-images.githubusercontent.com/4349208/90699521-9abac980-e2d7-11ea-9041-726bb22f41fd.png)
package.xml
![image](https://user-images.githubusercontent.com/4349208/90699537-a3130480-e2d7-11ea-9af8-bc65be0966ac.png)


I can probably unzip into a temp location and attempt to deploy the contents.
If I could deploy the zip directly that would be ideal.

**Comment by azlam-abdulsalam** [comment]
Got it, we are updating our create source package task for similar scenario (currently it just publishes the metadata, and you have to use checkout and deploy).  This will be combined (in addition) to a new Task called install Source package (which will automatically pull down the artifact) and install it.


Cheers,
Azlam

**Comment by azlam-abdulsalam** [comment]
Closing this issue, as it will be part of the updated Create Source Package/Delta Package Task. Hope it alleviates your issue
