### ISSUE TITLE
Build Issue:   @dxatscale/sfp-logger missing from package.json

### ISSUE THREAD

**Issue by pogilvieCB** [dxatscale/sfpowerscripts#1290]
**Describe the bug**
I cloned the repo so that I could read that code and from code red from a missing module after npm install.

**To Reproduce**
git clone

**Expected behavior**

All dependencies should be resolved after `npm install`.  

**Screenshots**

**Platform Details (please complete the following information):**
 platform independent

- OS: 
 - Version [e.g. CLI Version  eg: 1.6.6]
 - Salesforce CLI(sfdx cli) Version:
 - CI Platform: 

**Additional context**
Happy to create a PR if this is OK.

```
Projects/community/sfpowerscripts > git diff package.json                                                                                         sfpowerscripts (tmp)
diff --git a/package.json b/package.json
index ef60a58f..b3fe7ee2 100644
--- a/package.json
+++ b/package.json
@@ -22,7 +22,8 @@
         "ts-loader": "~9.4.2",
         "ts-node": "^8",
         "tslint": "^5",
-        "typescript": "^4.0.2"
+        "typescript": "^4.0.2",
+        "@dxatscale/sfp-logger": "^1.0.2"
     },
     "dependencies": {
         "neverthrow": "^4.2.1"
```

**Comment by azlam-abdulsalam** [comment]
@pogilvieCB  we use lerna in this repository, So can you try 'lerna bootstrap ' which will install all the dependencies.

**Comment by pogilvieCB** [comment]
OK, I see,  that's clearly called out in the build instructions.
