### ISSUE TITLE
having issue install sfpowerscript plugin in windows 11

### ISSUE THREAD

**Issue by Cherie-she** [dxatscale/sfpowerscripts#1291]
**Describe the bug**
The issue is raised on behalf of our client. 
The user is using a brand-new workstation, the os system of which is windows11, use has already installed sfdx-CLI and node, when he runs: sfdx plugins:install @dxatscale/sfpowerscripts it shows failed to install, the error message is provided under Additional context. 

**Steps Taken**
-  Uninstalled and reinstalled NPM and sfdx-cli updated them to latest version, installed yarn, node-gyp
- Added all the necessary environment variables to PATH
- Disconnected from the office network VPN 
- Restarted vscode and the machine
 
Tried all the methods provided in the below links: 
1. https://github.com/forcedotcom/lwc-dev-server-feedback/issues/3
2. https://developer.salesforce.com/forums/?id=9060G0000005m47QAA

**Expected behavior**
sfpowerscript should be installed successfully.  

**Platform Details:**
 - OS: windows 11
 - node version: 18.16.0
 - Salesforce CLI(sfdx cli) Version: 7.196.9
 - npm version: 9.6.4

**Additional context**
User had uninstalled and reinstall node himself before he raised the issue. 

**Error Message:** 
Error: Unable to update lock within the stale threshold
    at C:\Users\bng\AppData\Roaming\npm\node_modules\sfdx-cli\node_modules\yarn\lib\cli.js:78693:66
    at FSReqCallback.oncomplete (node:fs:198:23) {
  code: 'ECOMPROMISED'
}

Installing plugin @dxatscale/sfpowerscripts... failed
    Error: yarn add @dxatscale/sfpowerscripts@latest --non-interactive --mutex=file:C:\Users\bng\AppData\Local\sfdx\yarn.lock
    --preferred-cache-folder=C:\Users\bng\AppData\Local\sfdx\yarn --check-files exited with code 1

**Comment by azlam-abdulsalam** [comment]
@Cherie-she   I am not able to reproduce this issue. check whether you have installed nodejs with the right permissions and nodejs is installed with admin previleges

**Comment by vuha-acn** [comment]
Another article that I ran across on a VDI windows machine that you can also explore too if subsequent errors come - [https://github.com/Microsoft/nodejs-guidelines/blob/master/windows-environment.md#compiling-native-addon-modules](https://github.com/Microsoft/nodejs-guidelines/blob/master/windows-environment.md#compiling-native-addon-modules)

**Comment by Cherie-she** [comment]
@vuha-acn  Thanks for your reply Vu, I have tried the way mentioned in the article before I post which is Install node gyp by running: npm install -g node-gyp which succeeded. 
And then we tried to run 

- npm install --global --production windows-build-tools     

- npm install --global windows-build-tools@4.0.0

- npm install --global --production windows-build-tools --vs2015

all failed, error message: 
npm ERR! Downloaded vs_BuildTools.exe. Saved to C:\Users\bng\.windows-build-tools\vs_BuildTools.exe.
npm ERR!
npm ERR! Starting installation...
npm ERR! Downloading installers failed. Error: TypeError: 'process.env' only accepts a configurable, writable, and enumerable data descriptor

so we run : 
set NODE_OPTIONS=   
npm install -g windows-build-tools

still the same error. 

then we uninstalled windows-build-tools, clear cache, set env variable, install again still no luck.

Then we proceed to manually install python, add env variable, run the command still no luck. 

So far, nodejs, Python, npm, yarn, sfdx cli, gyp are installed and updated.
 
It could be a network issue too; I would wait and see user to back to the office next week to see if some miracle happens.

**Comment by vuha-acn** [comment]
Is there a VDI setup or Virtual Machine that you can replicate the error to confirm outside of the firewall? Unless their windows image is custom, it should be fairly easy to try to replicate if you have a Windows version to test on.

**Comment by Cherie-she** [comment]
@vuha-acn Thanks Vu for your suggestion, I will look into it.

**Comment by azlam-abdulsalam** [comment]
@Cherie-she  Can we close this?

**Comment by Cherie-she** [comment]
User went to their internal tech ops team to as for assistance but did not make any progress, their next action is to disable the firewall and security apps running in the background & see if it will resolve the issue. I doubt the issue is relevant to the tooling, the issue can be closed for now.
