### ISSUE TITLE
Field History Tracking Enabler skipped due to error

### ISSUE THREAD

**Issue by gethrok** [dxatscale/sfpowerscripts#1298]
When trying to deploy to Production with the Field History Tracking Enabler, it's skipped due to following error: 

Unable to process post deploy for Field History Tracking Enabler due to INVALID_OPERATION: rollbackOnError option must be true on a production org

**Comment by azlam-abdulsalam** [comment]
@gethrok  Thanks for raising this,  can you also point out the version you are using ?

**Comment by gethrok** [comment]
Yes sorry, The DX@Scale CI/CD Orchestrator -Version:20.30.3 -Release:March 23

**Comment by azlam-abdulsalam** [comment]
Thanks @gethrok  this has been fixed in 21.0.2 (April release). You can try the alpha release

**Comment by azlam-abdulsalam** [comment]
Thanks @gethrok  that was a silly error and missed test scenario in production 😁

**Comment by gethrok** [comment]
@azlam-abdulsalam  Thank you for the fast resolution!
