### ISSUE TITLE
Update  PMD version for sfpowerscripts docker file

### ISSUE THREAD

**Issue by mark10281996** [dxatscale/sfpowerscripts#1300]
PMD version should at least be updated to 6.54.0 as this handles false positive errors such as the new apex syntax like Assert statements and  UnusedLocalVariable false positive in dynamic SOQL.

Current version of PMD is: 6.48.0

**Comment by azlam-abdulsalam** [comment]
Due to a change in strategy and better tools available elsewhere, sfpowerscripts docker image will not carry PMD anymore. Recommend to use  alternate channels
