### ISSUE TITLE
Docker image problem on circleCI

### ISSUE THREAD

**Issue by sl-mikaelodokine** [dxatscale/sfpowerscripts#1307]
**Describe the bug**
Hello,
On circleCI when I use as executor your docker image ghcr.io/dxatscale/sfpowerscripts:latest I get an error when starting the image
However if I use an earlier version (ghcr.io/dxatscale/sfpowerscripts@sha256:72b2e81563bb06faa418125d62c8164df900aa84adc90294348f4cf2520f3b9a) I no longer have a problem

**Platform Details (please complete the following information):**
 - CI Platform: CircleCI

**Comment by azlam-abdulsalam** [comment]
Whats the error?

**Comment by sl-mikaelodokine** [comment]
Hello,

Sorry I forgot to specify that.
Here is the message:

> CircleCI was unable to start the container because of a userns remapping failure in Docker.
> 
> This typically means the image contains files with UID/GID values that are higher than Docker and CircleCI can use.
> 
> Checkout our docs https://circleci.com/docs/2.0/high-uid-error/ to learn how to fix this problem.
> Original error: CircleCI was unable to start the container because of a userns remapping failure in Docker.
> 
> This typically means the image contains files with UID/GID values that are higher than Docker and CircleCI can use.
> 
> Checkout our docs https://circleci.com/docs/2.0/high-uid-error/ to learn how to fix this problem.
> Original error: failed to register layer: Error processing tar file(exit status 1): Container ID 718322462 cannot be mapped to a host ID

**Comment by azlam-abdulsalam** [comment]
@sl-mikaelodokine  I believe this is because the container is having root user. Had planned for this, but never scheduled, will look into it

**Comment by azlam-abdulsalam** [comment]
@rody Can you have a look on this?

**Comment by azlam-abdulsalam** [comment]
Removing this out from July23 due to issues found in testing with echo in debian images, that could potentially impact usage of jq  with sf cli

@rody FYI

**Comment by rody** [comment]
Back to the drawing boars. @azlam-abdulsalam  would you mind sharing your findings so they are documented for future references, please?

From an early testing, it seems that basing the image on ubuntu is solving the edge case. I'll start with that so we have a quick fix.

**Comment by azlam-abdulsalam** [comment]
This should be fixed in the latest alpha images @sl-mikaelodokine can you confirm?

You can use the image here

https://github.com/dxatscale/sfpowerscripts/pkgs/container/sfpowerscripts-rc/129562645?tag=24.4.9-6244102517

**Comment by azlam-abdulsalam** [comment]
Closing this
