### ISSUE TITLE
Packages are ignored in Validate with Release Config

### ISSUE THREAD

**Issue by JoeffreyChaucer** [dxatscale/sfpowerscripts#1315]
**Describe the bug**
Currently, We are running the `sfdx sfpowerscripts:orchestrator:validateAgainstOrg` command on an empty sandbox to validate our packages. However, We encountered an error because the **"src-env-specific-pre"** package is being ignored according to our "ignoreOnStage validate" settings in the sfdx-project.json file. To address this, We tried using the **"thorough-release-config"** mode to include all packages, but it still it ignored the **"src-env-specific-pre"**. And Removing the "ignoreOnSetting validate" for the packages resulted in a new error stating that the _**package directory is empty**_.

**To Reproduce**

1. Use validate with release config (e.g. --mode=thorough-release-config)
2. Add package to release config
3. Add ignoreOnStage validate on package

**Expected behavior**
packages built and deployed during validate

**Screenshots**
![image](https://github.com/dxatscale/sfpowerscripts/assets/48306432/1400a401-3feb-4165-98b8-3fc5aeb06a64)
![image](https://github.com/dxatscale/sfpowerscripts/assets/48306432/c98c0f15-4d84-495a-9bb6-944c78864fa3)
![image](https://github.com/dxatscale/sfpowerscripts/assets/48306432/a6449cc3-1d76-4ac1-ba97-fd5f0364fe1c)
![image](https://github.com/dxatscale/sfpowerscripts/assets/48306432/5d62555f-0e2a-488b-b5dd-4720b0886595)

Remove  "ignoreOnSetting validate" for the packages.

![image](https://github.com/dxatscale/sfpowerscripts/assets/48306432/afd69cc5-3f1e-4425-b540-d24197c909ad)

**Platform Details (please complete the following information):**
 - OS: Linux
 - Version: Version:v21.1.0 -Release:April23
 - Salesforce CLI(sfdx cli) Version: 7.186.2
 - CI Platform: Buildkite

**Additional context**
Additional flags used `--disablesourcepkgoverride` and `--disableparalleltesting`

**Comment by azlam-abdulsalam** [comment]
@JoeffreyChaucer  As discussed with you in slack, this is an expected behaviour. Closing the ticket.
