### ISSUE TITLE
Simplify CLI usage by deprecating readvars

### ISSUE THREAD

**Issue by azlam-abdulsalam** [dxatscale/sfpowerscripts#133]
sfpowerscripts cli supports output variables, which are written to the environment of the host. However to consume this, a source readvars has to be issued before any other command. This makes the scripts verbose and defeat the purpose.

sfpowerscripts cli should store this output variable in its own environment config, and all tasks when provided with a non dereferenced  variable, should check the store and figure the value. It should also print the resolved variables

**Comment by aly76** [comment]
I propose that we keep the readvars script for now. It may still be useful for power users, who want access to output variables at the terminal layer.

**Comment by azlam-abdulsalam** [comment]
Sure we can keep it, but lets remove it from our main readme and add us a subsection
