### ISSUE TITLE
Vlocity Build Tool is removed from sfpowerscripts docker image

### ISSUE THREAD

**Issue by sumanthreddybolledla** [dxatscale/sfpowerscripts#1344]
**Describe the bug**
The latest version of sfpowerscripts is not supporting vlocity deployments. It seems like the vlocity installation command is removed from the dockerfile (refer to commit: https://github.com/dxatscale/sfpowerscripts/commit/847009c7f84f9033a8839bb795e1792c8d447424#diff-0503d81986f5a53b16cc3d4567f8806f9f64daca03998aa949be64ca3d867e76).

**To Reproduce**
1) make any change to vlocity package
2) run a validate/deploy/release operation

**Expected behavior**
vlocity components should be deployable

**Screenshots**
![image](https://github.com/dxatscale/sfpowerscripts/assets/19957368/3fd6934f-b061-40fe-9cf9-86438c0402fb)

**Platform Details (please complete the following information):**
 - OS: 
 - Version [e.g. CLI Version  eg: 1.6.6]
 - Salesforce CLI(sfdx cli) Version:
 - CI Platform: AzureDevops

**Additional context**

**Comment by azlam-abdulsalam** [comment]
@sumanthreddybolledla As discussed in slack, we are no longer carrying vbt in the cli, as there is no availability to a test bed at this stage, Please install it in the CI runs. Happy to discuss this further
