### ISSUE TITLE
sfp orchestrator:build -  Language bug upon package version creation

### ISSUE THREAD

**Issue by petter-eikeland** [dxatscale/sfpowerscripts#1347]
**Describe the bug**
When executing `sfp orchestrator:build`, language bugs that were fixed in sfdx version 7.192.2 still surface, more specifically:

```
Unable to create package due to 
Creation errors: 
1) Case.DefaultProcess: Picklist value: New not found
```

Occurs both locally and on Azure DevOps. **This blocks us from using the latest sfpowerscripts container** (March, April & June) and we have to keep using the September 22 release. 

**To Reproduce**
1.  Ensure your DevHub's default language is Norwegian (other non-English DevHubs might work as well)
2.  Add default record type to Case in project-scratch-def.json:     
```
"objectSettings": {
        "case": {
            "defaultRecordType": "default"
        }
    }

```

3. Set language parameter in  project-scratch-def.json:     
`"language": "en_US",`

4. Verify that a new package version is successfully built by executing `sfdx package version create`

5. Execute `sfp orchestrator:build -v myhuborg --branch main --diffcheck --buildnumber 123 -f config/project-scratch-def.json`

**Expected behavior**
A package version is successfully built by `sfp orchestrator:build`

**Actual Behavior**
"Old" sfdx error thrown: 
```
Unable to create package due to 
Creation errors: 
1) Case.DefaultProcess: Picklist value: New not found
```

**Platform Details (please complete the following information):**
 - OS: Mac OS
 - Version [e.g. CLI Version  eg: 1.6.6]: **22.5.5**
 - Salesforce CLI(sfdx cli) Version: **7.209.5**
 - CI Platform: N/A --> bug occurs locally as well

**Additional context**
I reported the bug to sfdx ([bug 1](https://github.com/forcedotcom/cli/issues/1921), [bug 2](https://github.com/forcedotcom/cli/issues/1981)) , and it was fixed in [the following packaging PR](https://github.com/forcedotcom/packaging/pull/239)

Might be that `sfp` does not utilize the language parameter, or objectSettings values?

**Comment by azlam-abdulsalam** [comment]
Will be fixed as part of July23 when core libs are updated? Are you blocked?

**Comment by petter-eikeland** [comment]
Not a major blocker, only blocker for using new functionality (new picklist patch, dependency expand, etc.) 

We can wait until July 23 ✌️

**Comment by azlam-abdulsalam** [comment]
@petter-eikeland is it part of #1253 as well?

**Comment by petter-eikeland** [comment]
Good question. I don't think the issue is part of it. However, we can close that issue. I didn't find the use case for it after all. It was solved by [the language param in project-scratch-json](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_scratch_orgs_def_file.htm#scratch_org_definition_file_options)

**Comment by azlam-abdulsalam** [comment]
This is fixed in July 23,
