### ISSUE TITLE
orchestrator:prepare warning about invalid property "seedMetadata"

### ISSUE THREAD

**Issue by pogilvieCB** [dxatscale/sfpowerscripts#1349]
**Describe the bug**
Here's the Salesforce description of "seedMetada"
```
Seed metadata is available to standard value sets only. If your package depends on standard 
value sets, you can specify a seed metadata directory that contains the value sets.
```
[seedMetadata](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_unlocked_pkg_config_file.htm#:~:text=to%20release%20notes.-,seedMetadata,-No)

Appears that this property is unknown to sfpowerscripts and it complains about it.

```
-------------------------------------------------------------------------------------------
sfpowerscripts  -- The DX@Scale CI/CD Orchestrator -Version:22.6.1 -Release:June 23
-------------------------------------------------------------------------------------------
The following attributes are not recognized by sfpowerscripts, You might need to remove them
The sfdx-project.json is invalid, Please fix the following errors

1: /packageDirectories/2: must NOT have additional properties {
    "additionalProperty": "seedMetadata"
}
```

**To Reproduce**
Add the property "seedMetadata" to an sfdx-project.json file as documented above

**Expected behavior**

Should not issue warning about supported property.

**Screenshots**

![image](https://github.com/dxatscale/sfpowerscripts/assets/70237646/4d86dcf9-592f-413c-933a-abffbcfe16bb)

**Platform Details (please complete the following information):**
 - OS:  Ubuntu Latest
 - Version [e.g. CLI Version  eg: 1.6.6]. sfp v 22.6.1
 - Salesforce CLI(sfdx cli) Version:
 - CI Platform: Github Actions

**Additional context**

**Comment by azlam-abdulsalam** [comment]
@pogilvieCB Is it otherwise working as expected? Probably will get it fixed along with updates to the core libraries in July 23

**Comment by pogilvieCB** [comment]
No, it seems to be working fine.   A number of things were broken during the upgrade so we're looking at all the warning messages carefully.   No reason for this not to wait for the next scheduled release.
