### ISSUE TITLE
Improve Error Output for the profile reconcile command

### ISSUE THREAD

**Issue by Schuchie** [dxatscale/sfpowerscripts#1350]
**Describe the bug**
Currently the log output is cutted at the profile reconcile command, if the profile xml is not valid.

**To Reproduce**
* Make a profile xml invalid by removing one element tag
* Rune the following command
*  `sfp profile:reconcile -u dev -f "src-access-management/profile/main/default/profiles/" --loglevel trace`

**Expected behavior**
The error contains the related profile api name or file name and the problem element.

**Screenshots**
Log output:
![image](https://github.com/dxatscale/sfpowerscripts/assets/18148112/0a9db7be-ba88-4d5f-abd9-c4c8bcbcf5a1)

**Platform Details (please complete the following information):**
 - OS: Mac OS 13.4.1
 - Version: @dxatscale/sfpowerscripts/22.5.5 darwin-arm64 node-v18.11.0
 - Salesforce CLI(sfdx cli) Version: sfdx-cli/7.207.5 darwin-arm64 node-v18.11.0
 - CI Platform: Local

**Additional context**
Error Message in project: `sfpowerscripts/packages/sfprofiles/src/impl/source/reconcileWorker.ts:98`

**Comment by azlam-abdulsalam** [comment]
@ethan-sargent  Can you have a look at this one?

**Comment by ethan-sargent** [comment]
PR above should make this look like the following: 
![image](https://github.com/dxatscale/sfpowerscripts/assets/17370760/00a27d94-9aaa-4a3f-ace7-d21a170bb295)
