### ISSUE TITLE
Bad namespaced class names from apex-node break test retry logic

### ISSUE THREAD

**Issue by JonnyPower** [dxatscale/sfpowerscripts#1362]
**Describe the bug**

When using sfp apextests:trigger to run tests in a namespaced org, the test retry logic fails due to apex class full names being provided by upstream @salesforce/apex-node library (https://github.com/forcedotcom/salesforcedx-apex/issues/296)

Waiting for an upstream fix in 4.x is problematic, so opening issue to track work with a fix within dx@scale rather than waiting for upstream fix.

**To Reproduce**

1. Create a scratch org with a namespace
2. Create unit tests that will hit a timeout or lock exception (I'm replicating reliably on our ISV product, but could also replicate with contention on org custom settings I suspect)
3. Run unit tests
4. apextests:trigger will run async then report failures and queue failed classes for a retry
5. class names are invalid (`NS.NS__Foo` instead of `NS.Foo`)

**Expected behavior**

1. Should be able to retry test failures in namespaced test classes

**Screenshots**

![image](https://github.com/dxatscale/sfpowerscripts/assets/1668924/7ed9fc94-5cde-40d4-a7fc-b84fe4e6e351)

**Additional context**

- There is an open issue with upstream project, with a PR - the contributor has no signed the CLA. https://github.com/forcedotcom/salesforcedx-apex/issues/296 and https://github.com/forcedotcom/salesforcedx-apex/pull/297
- From discussion with Azlam, preference is to fix now rather than waiting for 4.x upstream change due to complications introduced by Salesforce in the 4.x packages

**Comment by JonnyPower** [comment]
@azlam-abdulsalam can you assign to me? created this for branch issue reference

**Comment by azlam-abdulsalam** [comment]
Thanks for the detailed bug report @JonnyPower
