### ISSUE TITLE
Potential fix for vm2

### ISSUE THREAD

**Issue by rygramer** [dxatscale/sfpowerscripts#1378]
re: #1366. I think bumping this will remove the dependency tree to vm2. Looks like they fixed the dependency in this version when they bumped @salesforce/source-deploy-retrieve from 8.6.0 to 9.3.4.
https://github.com/dxatscale/sfpowerscripts/blob/5259180f1f0ab952255d44d5bf7e6bfb8ee8691b/packages/core/package.json#L30

**Comment by azlam-abdulsalam** [comment]
Fantastic, thanks @rygramer . I have updated the same. Closing the issue
