### ISSUE TITLE
request and request-promise-native vulnerability

### ISSUE THREAD

**Issue by rygramer** [dxatscale/sfpowerscripts#1382]
These two packages are no longer maintained, and [Snyk has reported an issue with the `request` package related to Server-side Request Forgery.](https://security.snyk.io/vuln/SNYK-JS-REQUEST-3361831)

jsforce went through a similar analysis and remediation here: https://github.com/jsforce/jsforce/issues/1312

I wish I could help, but this is out of my wheelhouse. I do think this is an important fix to push through.

https://github.com/dxatscale/sfpowerscripts/blob/185b6fbcbd2d847619b021eaf48544506191cba2/packages/sfprofiles/package.json#L74-L75

**Comment by rygramer** [comment]
@azlam-abdulsalam I was looking into this a bit more. Looks like the only usage of `request` / `request-promise-native` in the entire `sfp` library is in this method:
https://github.com/dxatscale/sfpowerscripts/blob/5ab19002f66fa843a2a4c6605829c41ad87cea65/packages/sfprofiles/src/utils/scratchOrgUtils.ts#L32-L47
It doesn't look like this method is referenced anywhere in the codebase. (`PoolCreateImpl` is using `ScratchOrgLimitsFetcher`, the latter not having a dependency to either `request` / `request-promist native`, nor `sfprofiles`):
https://github.com/dxatscale/sfpowerscripts/blob/5ab19002f66fa843a2a4c6605829c41ad87cea65/packages/core/src/scratchorg/pool/PoolCreateImpl.ts#L57
Perhaps the vulnerable method is an artifact of the past, and can simply be removed (which would also eliminate the dependency on `request` and `request-promise-native`)?? 🤞

**Comment by azlam-abdulsalam** [comment]
Wohooo! Thanks @rygramer  Checking this one
