### ISSUE TITLE
sfp pool:org:delete stopped working in July 23

### ISSUE THREAD

**Issue by petter-eikeland** [dxatscale/sfpowerscripts#1388]
**Describe the bug**
Running `sfp pool:org:delete` in July 23 gives you the following error:
```
Error: Either the scratch org doesn't exist or you do not have the correct
     permissions, Failed with Cannot read properties of undefined (reading 
    'Id')
```

Same command works as expected in June 23

**Screenshots**
***July 23***
![image](https://github.com/dxatscale/sfpowerscripts/assets/97173615/d68ca4de-2f60-4196-a3ac-442eaf388d31)

***June 23***
![image](https://github.com/dxatscale/sfpowerscripts/assets/97173615/2dd1c7dc-e601-490b-9cd8-6880c19bcaeb)

**Platform Details (please complete the following information):**
 - OS: Linux
 - Version [e.g. CLI Version  eg: 1.6.6] 23.4.2
 - Salesforce CLI(sfdx cli) Version: Unsure
 - CI Platform: Azure DevOps

**Comment by mitchi-droid** [comment]
I have the same issue using Github Actions. 2 weeks ago it worked and with latest version of 23.4.2 it stopped working and throws the error mentioned above.

**Comment by azlam-abdulsalam** [comment]
Looking into it

**Comment by mitchi-droid** [comment]
@azlam-abdulsalam , splendid

**Comment by mitchi-droid** [comment]
@azlam-abdulsalam , will you know when there will be a fix for this issue? Or if you know what causes this to happen, is there any workaround for that? Thanks :)

**Comment by petter-eikeland** [comment]
@mitchi-droid You could simply downgrade the container of your pipeline to the June Release while you're waiting for a fix:

`container: ghcr.io/dxatscale/sfpowerscripts:22.6.1-5456000622`

**Comment by azlam-abdulsalam** [comment]
Thanks for the patience @petter-eikeland  and @mitchi-droid ,  this is now resolved. will be rolling out in December 23

**Comment by mitchi-droid** [comment]
@azlam-abdulsalam , cool, thanks a lot. In the end, small priority issue but thanks for keeping the base running. Wonderful job. 🫵💪🥳

**Comment by azlam-abdulsalam** [comment]
You could try the latest alpha builds for this one 

The container for the same is 
ghcr.io/dxatscale/sfpowerscripts-rc:25.0.8-6621969031

https://github.com/dxatscale/sfpowerscripts/pkgs/container/sfpowerscripts-rc

**Comment by petter-eikeland** [comment]
Works like a charm! 
<img width="775" alt="image" src="https://github.com/dxatscale/sfpowerscripts/assets/97173615/97ac2ee4-e950-4648-a49a-d57c36f3106d">
