### ISSUE TITLE
sfpowerscripts  apextests:trigger namespace issues while running in parallel

### ISSUE THREAD

**Issue by adarsha45** [dxatscale/sfpowerscripts#1389]
While running sfpowerscripts  apextests:trigger  -l RunApexTestSuite --apextestsuite 'CQAuditTestSuitenew' -u freshorg
one test got failed in parallel **( e.g ada__OPQX_Test_6924_Cross_Privilege . here ada represents the namespace ,concatenated after  the test ran from org )** and then it started running tests synchronously which is expected.
But after it started to run that particular test which got failed synchronously it is adding extra namespace again 
and the failed error is :
**This class name's value is invalid: ada.ada__OPQX_Test_6924_Cross_Privilege. Provide the name of an Apex class that has test methods.**

**Comment by azlam-abdulsalam** [comment]
@adarsha45  Can you provide version details?  A fix was merged for this recently

@JonnyPower  do you have ideas?

**Comment by adarsha45** [comment]
we are currently using the api version 57 .
@azlam-abdulsalam  @JonnyPower 
@dxatscale/sfpowerscripts/22.6.1

**Comment by azlam-abdulsalam** [comment]
Please update to https://github.com/dxatscale/sfpowerscripts/releases/tag/%40dxatscale%2Fsfpowerscripts%4023.4.2 for the fixes.

I am closing this one.
