### ISSUE TITLE
this.config.getPluginsList is not a function

### ISSUE THREAD

**Issue by ForgacsMartin** [dxatscale/sfpowerscripts#1392]
We are using the following command in our yml file in azure pipeline:

- task: sfpwowerscript-installsfdx-task@9
  displayName: "Install SFDX"
  inputs:
    salesforce_api_version: 53.0
    sfdx_cli_version: latest
    plugins: "sfdx-git-delta@5.3.1"

During the runs of the pipeline it fails with the following error message:

TypeError: this.config.getPluginsList is not a function
##[error]Command failed: sfdx force:config:set apiVersion=53.0
TypeError: this.config.getPluginsList is not a function

The error was reported through the CLI:
https://github.com/forcedotcom/cli/issues/2426

The issue is closed but the azure pipeline is still not working,
Could you please take a look why it happens?

**Comment by azlam-abdulsalam** [comment]
@ForgacsMartin  This task above is part of sfpowerscripts azure pipelines extension which was deprecated for 2 years,  Please do not use it further
