### ISSUE TITLE
Similarly-named packages are built unnecessarily

### ISSUE THREAD

**Issue by thraco** [dxatscale/sfpowerscripts#1396]
**Describe the bug**
Additional packages are built unnecessarily when code changes in a similarly-named package.

**To Reproduce**
- Project contains two packages on similar paths (For this example, assume there are two packages located at `src/integrations` and `src/integrations-core`)
- A change is made to the package with the longer/hyphenated name (`src/integrations-core`)

**Expected behavior**
During the build, the change to integrations-core are found and a new integrations-core package is built.

**Screenshots**
During the build, the change to integrations-core are found and two new packages are built: integrations-core and integrations. On comparing the previous and new packages for integrations, no differences are found.

**Platform Details (please complete the following information):**
 - OS: Ubuntu 22.04.3 LTS
 - Version [e.g. CLI Version  eg: 1.6.6] 21.1.0
 - Salesforce CLI(sfdx cli) Version: 7.194.1
 - CI Platform: GitHub Runners

**Additional context**
Screenshots of the log files showing this issue are attached.
![integrations-core](https://github.com/dxatscale/sfpowerscripts/assets/1449844/37a9a474-22e8-4db7-a2dc-54c7e1f7befb)
![integrations](https://github.com/dxatscale/sfpowerscripts/assets/1449844/8f6e1793-aca2-407c-8d14-77a7d4d18cec)

**Comment by azlam-abdulsalam** [comment]
@thraco  Thanks for raising this. Will be looking at it.  Interesting one :) I think i have an idea why it happens probably a bug with how the tags are parsed

**Comment by azlam-abdulsalam** [comment]
@thraco  This  is the  issue area 

https://github.com/dxatscale/sfpowerscripts/blob/7c5d9d4be4d2d4036175f750f3b0444db5223d14/packages/core/src/package/diff/PackageDiffImpl.ts#L74-L80
