### ISSUE TITLE
Updating Azure DevOps variable group variable from Azure Release pipeline

### ISSUE THREAD

**Issue by ayadav4** [dxatscale/sfpowerscripts#140]
Hi Team,

I am looking for to update Azure DevOps variable group variable from release pipeline, Any help on this, would be a great favor.

**Comment by azlam-abdulsalam** [comment]
Can you elaborate the usecase?

**Comment by ayadav4** [comment]
In Azure DevOps Library- I have defined a variable group. This variable group consists some variables.
This variable group is linked to Azure Release pipeline.  I am changing one of the variable group variable value in release pipeline at the time of execution . I want this new value to save back into variable group variable.

**Comment by vuha-acn** [comment]
For the new value that is saved back into the variable group variable, does that again in future runs of the Release Pipeline get updated and replaced? I don't see the use case for this to be handled by the current SFPowerscripts command.   Also, if you could provide the task and more details on the variable in hand that is being updated, that could provide more context.

**Comment by azlam-abdulsalam** [comment]
@ayadav4  Can you go through these articles?
https://cloudarchitected.com/2019/10/updating-variable-groups-from-an-azure-devops-pipeline/
