### ISSUE TITLE
sfdx sfpowerscripts:orchestrator:quickbuild - TypeError: Cannot read properties of undefined (reading 'prototype')

### ISSUE THREAD

**Issue by emoraiss** [dxatscale/sfpowerscripts#1406]
**Describe the bug**
When running sfpowerscripts:orchestrator quickbuild I receive TypeError: Cannot read properties of undefined (reading 'prototype')

**To Reproduce**
@salesforce/cli/2.6.9 win32-x64 node-v18.15.0
@dxatscale/sfpowerscripts 23.4.2
sfdmu 4.30.0
sfpowerkit 6.1.0

Run one of the following commands:
sfdx sfpowerscripts:orchestrator:quickbuild -v devhubname--buildnumber xxx --branch branchname
sfdx sfpowerscripts:orchestrator:quickbuild --diffcheck -v devhubname

**Expected behavior**
quickbuild runs without error

**Screenshots**

**Platform Details (please complete the following information):**
 - OS: Windows 11 Home
 - Version [e.g. CLI Version  eg: 1.6.6]
 - Salesforce CLI(sfdx cli) Version:
 - salesforce/cli/2.6.9
 - NodeJs Version: 18.15.0
 - Plugin versions:
  @dxatscale/sfpowerscripts 23.4.2
  sfdmu 4.30.0
  sfpowerkit 6.1.0

**Additional context**
Yesterday my sfdx stopped working, and I uninstalled and reinstalled the Salesforce CLI. Today I also reinstalled the plugins and I was able to use some sfpowerscripts commands as the pool list and fetch a scratch org, but I failed when trying to build the packages using orchestrator build. I've also authorized again the DevHub.

**Comment by azlam-abdulsalam** [comment]
@emoraiss  sfpowerscripts latest version is no longer a sfdx plugin, you can install it using npm and then use as 'sfp'. globally
