### ISSUE TITLE
Apextest filure with unknown error 

### ISSUE THREAD

**Issue by adarsha45** [dxatscale/sfpowerscripts#1408]
i am currently using the code sfpowerscripts apextests:trigger -l RunApexTestSuite to run apextestsuite parallely
but it keeps on automatically throwing errors and killing the process in uncertain manner. sometimes it is success and sometime not ,and not rerunning after the failure again .
the errors throws are :
Error: Cannot read properties of undefined (reading 'Status')
No test report files were found. Configuration error?
another error :
System.DmlException: Insert failed. First exception on row 0; first error: UNKNOWN_EXCEPTION, common.udd.object.DmlOperationException: []

**Comment by azlam-abdulsalam** [comment]
Thanks @adarsha45 , This is currently fixed in 24.4.2.  Can you let me know if it solves your  issue.

**Comment by adarsha45** [comment]
@azlam-abdulsalam  it solved the previous issue  , but now the error we are facing is ...
/usr/local/lib/node_modules/@dxatscale/sfpowerscripts/node_modules/jsforce/lib/http-api.js:252

    return new HttpApiError(error.message, error.errorCode);

           ^
ERROR_HTTP_503: upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: delayed connect error: 111
is it sf issue or sf powerscripts ?
