### ISSUE TITLE
while creating a scratch org is it possible to have your managed and unmanged packages in your pooled orgs >

### ISSUE THREAD

**Issue by adarsha45** [dxatscale/sfpowerscripts#1410]
scenario : i have a project with multiple packages for example .
    {
      "path": "ext/form/force-app",
      "package": "ada User Interface",
      "versionName": "CQ Winter 2023",
      "versionNumber": "13.1.0.NEXT",
      "default": false,
      "dependencies": [
        {
          "package": "cqadada"
        }
      ],
      "definitionFile": "config/project-scratch-def.json",
      "ancestorId": "HIGHEST"
    },
    now how to create a pool with orgs already containing these packages ,
    and is it possible to directly deploy the content of path (unmanaged ) instead of managed install ?
    if possible can i have a refrence project that have dependency installed ?

**Comment by azlam-abdulsalam** [comment]
@adarsha45  Please read the document here
https://docs.dxatscale.io/sfpowerscripts/prepare

For more queries please hit the slack channel at 

https://launchpass.com/dxatscale
