### ISSUE TITLE
Work Item Filters Does not work with multiple filters

### ISSUE THREAD

**Issue by brandonmikeska** [dxatscale/sfpowerscripts#1415]
**Describe the bug**
When attempting to use workItemFilters for change logs, if you try to use multiple filters, it puts them all as one comma separated filter.

**To Reproduce**
Add multiple filters to your release definition.

**Expected behavior**
When the WorkItemUpdater is attempting to match the filters, the for of should loop the filters instead of just always finding one filter.

**Screenshots**
N/A

**Platform Details (please complete the following information):**
 - OS: Mac/Windows
 - Version [e.g. CLI Version  eg: 1.6.6]: Latest
 - Salesforce CLI(sfdx cli) Version: Latest
 - CI Platform: GitHub

**Additional context**
This line https://github.com/dxatscale/sfpowerscripts/blob/524c283992508adcb413e2f3303c39558400a31d/packages/sfpowerscripts-cli/src/impl/release/ReleaseImpl.ts#L82

**Currently is:**
workitemFilters.push(releaseDefinition.changelog?.workItemFilters);

**Could be changed to:**
workitemFilters.push(...releaseDefinition.changelog?.workItemFilters);

I don't have access to create a branch for a pull request but I think if you do this and update the WorkItemUpdater.test.ts to have two string values it should cover the code and a good test to see it not work before this change.

**Comment by azlam-abdulsalam** [comment]
@brandonmikeska  you can create a PR from a fork, please feel to create one!

**Comment by brandonmikeska** [comment]
@azlam-abdulsalam done https://github.com/dxatscale/sfpowerscripts/pull/1429

**Comment by azlam-abdulsalam** [comment]
Thanks @brandonmikeska , its merged
