### ISSUE TITLE
Dead Link in README.md: "Getting Started with CI/CD"

### ISSUE THREAD

**Issue by dunks184** [dxatscale/sfpowerscripts#1425]
**Describe the bug**
Dead link.

There's a link in the README.md that reads as follows:

```
Getting started guides for popular CI/CD platforms along with reference pipelines are available [here](https://docs.dxatscale.io/reference-implementation/github)
```

This leads to a "Page not found".

**To Reproduce**
Click the link!

**Expected behavior**
To be taken to a page with guides on getting started with CI/CD.

**Screenshots**
<img width="781" alt="image" src="https://github.com/dxatscale/sfpowerscripts/assets/13901837/620e3639-dc48-4322-bc69-37ed62dea0f5">
<img width="493" alt="image" src="https://github.com/dxatscale/sfpowerscripts/assets/13901837/e741b924-d71b-4e7f-95de-b2cac10e9c94">

**Platform Details (please complete the following information):**
 - OS: N/A
 - Version [e.g. CLI Version  eg: 1.6.6] N/A
 - Salesforce CLI(sfdx cli) Version: N/A
 - CI Platform: N/A

**Additional context**
I would have just put up a PR but didn't know the correct page for the link ref.

**Comment by azlam-abdulsalam** [comment]
Thanks @dunks184 , its been resolved
