### ISSUE TITLE
Some sfpowerscripts commands not available to use with any docker image

### ISSUE THREAD

**Issue by MeryamMeilleursagents** [dxatscale/sfpowerscripts#1427]
**Describe the bug**
 We use the latest docker image for sfpowerscripts.
 We want to migrate from sfdx to sf.
 But somme commands don't work with Docker image

**To Reproduce**
 using circle ci, we use the lastest Docker image (25.0.6-6556347074)

![image](https://github.com/dxatscale/sfpowerscripts/assets/78353502/f4ce11d0-35dc-4fc3-b553-b17dda0df999)

 And while execusting somme commands like 'sf sfpowerscripts orchestrator validate' it indicates "Error: Command sfpowerscripts:orchestrator:validate not found"
 
![image](https://github.com/dxatscale/sfpowerscripts/assets/78353502/6e0553ea-d61f-4df7-915f-b1e04dcd6f4b)

**Expected behavior**
sfpowerscripts commands working

**Platform Details (please complete the following information):**
 - OS: ubuntu-2204:2023.04.2
 - Salesforce CLI(sfdx cli) Version: @salesforce/cli/2.10.2 linux-x64 node-v18.18.2
 - CI Platform: circleci

**Comment by azlam-abdulsalam** [comment]
sfpowerscripts is no longer a plugin, use sfp orchestrator:validate or sfpowerscripts orchestrator:validate for sfpowerscripts commands

**Comment by azlam-abdulsalam** [comment]
I am closing this issue, please feel free to open a new one if you are facing any issues
