### ISSUE TITLE
Error in GitHub Workflow: sfpowerscripts Orchestrator:Prepare with auth:accesstoken:store

### ISSUE THREAD

**Issue by GiladKW** [dxatscale/sfpowerscripts#1438]
**Description**
I am attempting to run the sfpowerscripts orchestrator:prepare command within a github workflow. Even though the authentication method used is auth:accesstoken:store, the following error is thrown:

```
    Error: Unable to execute command .. Error: Pools have to be created using 
    a DevHub authenticated with auth:web or auth:store or 
    auth:accesstoken:store
 ```

**Steps To Reproduce**

- Authenticate using JWT with `sfdx auth:jwt:grant`.

- Extract AccessToken using `sfdx force:org:display`.
- Deauthenticate/remove the JWT auth configuration [`sfdx auth:logout`, `rm -f ~/.sfdx/*.json`].
- Authenticate using the extracted AccessToken with `sfdx auth:accesstoken:store`.
- Run the `sfpowerscripts orchestrator:prepare` command

**Platform Details (please complete the following information):**
- OS: Ubuntu 22.04.3
- Salesforce CLI(sfdx cli) Version: @salesforce/cli/2.14.6 linux-x64 node-v18.18.2
- CI Platform: Github

**Comment by rygramer** [comment]
@GiladKW the error message is misleading. dx@scale does not support the jwt login flow. There's a convo about it here: https://flxbl-io.slack.com/archives/CN9N54GF5/p1693248029499739

**Comment by fransf-wtax** [comment]
@rygramer How do we get access to this Slack workspace? Thanks!

**Comment by rygramer** [comment]
https://launchpass.com/flxblio 😁

**Comment by azlam-abdulsalam** [comment]
Closing this one as its invalid
