### ISSUE TITLE
Parallel tests are failing while using command "sfpowerscripts apextests:trigger -l RunApexTestSuite --apextestsuite testsuite0 -u org_name

### ISSUE THREAD

**Issue by adarsha45** [dxatscale/sfpowerscripts#1453]
![Screenshot_1_ada_](https://github.com/dxatscale/sfpowerscripts/assets/45120888/e858d5c3-9ef6-4f9d-8454-dc74430e3e33)

- many tests are showing failure with same error log , sometimes get fixed while rerun but is occurring multiple times.
- in the above-mentioned file three parallel execution are same but one of them in random order is getting this issue .

Error
System.DmlException: Insert failed. First exception on row 0; first error: INVALID_CROSS_REFERENCE_KEY, You can only assign users to permission set groups that have the "Updated" status.: []
Stacktrace
Class.compliancequest.SQX_Test_Account_Factory.assignPermissionSetGroup: line 386, column 1
Class.compliancequest.SQX_Test_1822_ComplaintQtyNotNegative.givenComplaint_ComplaintQuantityCannotBeNegative: line 38, column 1

@oscarrenalias  @rody

**Comment by azlam-abdulsalam** [comment]
@adarsha45  This is not a sfp issue,  You will be able to reproduce the same issue by running the apex test suite in the UI.  By default, salesforce executes these tests in parallel,  You might want to check these tests or probably, need to change setting in the org to run synchronously

**Comment by rody** [comment]
Hello @adarsha45,
For an explanation of the `INVALID_CROSS_REFERENCE_KEY` you can have a look at: https://www.salto.io/blog-posts/invalid-cross-reference-id
