### ISSUE TITLE
PMD Analysis - Request Support for YAML-based Pipelines

### ISSUE THREAD

**Issue by pb-seiso** [dxatscale/sfpowerscripts#146]
It appears that PMD Apex analysis currently only supports the Azure DevOps Classic (GUI-based) pipeline:
https://github.com/Accenture/sfpowerscripts/blob/master/azure-pipelines/task-specifications/testing-tasks/run-a-static-analysis-of-apex-classes-with-pmd.md

We would strongly prefer to use YAML pipelines so we can codify the logic for flexibility and version control. Is there any plan to implement this as a feature?

**Comment by Caitlyn-Mills** [comment]
Hi, 
This task is available in yaml please see this [link](https://dxatscale.gitbook.io/sfpowerscripts/azure-pipelines/task-specifications/testing-tasks/run-a-static-analysis-of-apex-classes-with-pmd). There is a 'Yaml Example' tab in the parameters section. 

If this doesn't answer your question, please clarify. 

Caitlyn

**Comment by pb-seiso** [comment]
Hi Caitlyn,

Thanks for the reply. I was actually able to resolve this by eliminating the step prior to my PMD task. When the task (unit testing) failed, I received generic output from the PMD step:

```
Evaluating: SucceededNode()
Result: False
```

I can explain what lead to my confusion though. Per [this link to the PMD task](https://github.com/Accenture/sfpowerscripts/blob/master/azure-pipelines/task-specifications/testing-tasks/run-a-static-analysis-of-apex-classes-with-pmd.md), there's the line "Please note this enhancement only works with ‘Classic’ pipelines only".

In Azure DevOps, there appears to be a difference between a pipeline that is created as YAML versus a pipeline created using the GUI-editor (aka "Classic"). While YAML can be exported from Classic pipelines, it seems like there are fundamental differences between how the two operate. You can see references to that in threads like [this](https://github.com/MicrosoftDocs/azure-devops-docs/issues/6828#issuecomment-571527248). 

Based on the documentation, it appears the PMD task wasn't working in Classic pipelines at one point, but is no longer the case.

Hope that helps!
