### ISSUE TITLE
Deploy destructive manifest breaks when destructiveChanges.xml file not generated

### ISSUE THREAD

**Issue by Majd-Soufan** [dxatscale/sfpowerscripts#15]
DeployDestructiveManifestToOrg task does not have a flag to prevented from breaking when the destructiveChanges.xml is not generated. Can you add a check box for that on the AzureDevOps pipeline task?

**Comment by Majd-Soufan** [comment]
Any progress on this issue @aly76 ?

**Comment by aly76** [comment]
Hi @Majd-Soufan , sorry it's been busy lately - will look into this later this week.

**Comment by azlam-abdulsalam** [comment]
@Majd-Soufan  We are reprioritizing this, Sorry for that, will feature in our next milestone .

As a workaround, you can utilize azure pipeline condition statement to skip on failure for now

**Comment by azlam-abdulsalam** [comment]
@aly76  Moving to milestone 15?

**Comment by Majd-Soufan** [comment]
Thank you for responding to this. When should I expect the new version of the ADO task(with skipping functionality) to be published?

**Comment by azlam-abdulsalam** [comment]
We should be hitting prod next week, working on docs!
