### ISSUE TITLE
Export Metadata from an org null error

### ISSUE THREAD

**Issue by Caitlyn-Mills** [dxatscale/sfpowerscripts#156]
Issue from slack: trying to auth to a SF instance and extract the current metadata to a directory.  I am getting an error on the export.  See the attachments below. Any idea where I could get some more details on the error?

![image](https://user-images.githubusercontent.com/63215232/94379049-f5fc9900-016c-11eb-8b9e-cf31fcd9bb77.png)
![image](https://user-images.githubusercontent.com/63215232/94379058-0c0a5980-016d-11eb-9fab-a303b7d96cc1.png)

**Comment by kknapp1** [comment]
@Caitlyn-Mills, i think, if you add the build variable "debug" and set value to "true" you'll get quite a bit more detailed logging. can you try that and post the log?

**Comment by Caitlyn-Mills** [comment]
Thanks @kknapp1 this is an issue raised by a member on slack, which I am reporting here. We have suggested trying running the command locally using sfpowerkits command directly to triage. 
Thanks 👍

**Comment by Caitlyn-Mills** [comment]
Closing as we have had no response.
