### ISSUE TITLE
Azure task "sfpwowerscript-installsfdx-task@6" fails with "##[error]Command failed: sfdx plugins:install sfpowerkit@latest"

### ISSUE THREAD

**Issue by ggciteo** [dxatscale/sfpowerscripts#17]
I just installed latest version sfpowerscripts in Azure devops : 13.8000.9 (Latest)
I ran the task ```sfpwowerscript-installsfdx-task@6```
And it fails with : 
``` 
Installing Plugin sfpowerkit@latest
'sfdx' is not recognized as an internal or external command,
operable program or batch file.
##[error]Command failed: sfdx plugins:install sfpowerkit@latest
'sfdx' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by azlam-abdulsalam** [comment]
Can you let me know which agent you are running this on?

**Comment by ggciteo** [comment]
Hi,
Windows server 2019
vsts-agent-win-x64-2.168.2
node v12.16.3
Let me know if you want some more informations...

**Comment by azlam-abdulsalam** [comment]
Are you using a microsoft hosted agent or self hosted agent?

**Comment by ggciteo** [comment]
Host is a VM on MS Azure

**Comment by azlam-abdulsalam** [comment]
@ggciteo Can you confirm whether npm and yarn is installed in your host?

**Comment by azlam-abdulsalam** [comment]
@aly76  We will have to add a prerequisite check and show proper error messages

**Comment by ggciteo** [comment]
I installed only npm, as I got an error message saying npm is lacking.
I was thinking yarn is no use...
So, I just installed yarn, and still the same error message.

**Comment by azlam-abdulsalam** [comment]
I am not sure what is causing it, i think the best course of action is to skip this task and install the sfdx cli and the sfpowerkit plugin manually.

My guess it could be related to permissions as these are tried to be install globally

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by ggciteo** [comment]
Hi there,
It works if I install sfdx manually.
It then install sfpowerscript automatically.
