### ISSUE TITLE
sfpowerscripts-pmdanalysis-tab doesn't display any issues

### ISSUE THREAD

**Issue by rokam** [dxatscale/sfpowerscripts#183]
Even after running the analyzewithpmd task, I'm unable to obtain data into the PMD APEX Analysis tab.
```yaml
- task: sfpwowerscripts-analyzewithpmd-task@6
  displayName: 'Analyze using PMD'
```

**Comment by rokam** [comment]
I've just updated to the latest version and it's now working.

**Comment by Caitlyn-Mills** [comment]
Thanks @rokam, glad you were able to solve the issue.
