### ISSUE TITLE
Prepare/Validate command to support installation of managed packages which has keys

### ISSUE THREAD

**Issue by azlam-abdulsalam** [dxatscale/sfpowerscripts#336]
Orchestrator:prepare currently doesn't provide an option to install any dependent managed packages that have keys. The underlying command sfpowerkit package dependencies install  does allow support of keys.

The plugin section of sfdx-project.json should be used to specify the keys for packages that are matched by alias.

**Comment by aly76** [comment]
Already implemented

**Comment by azlam-abdulsalam** [comment]
Reopening this, as the keys has to move into sfdx-project.json inside plugins. The current implementation of key passed through command line is not sufficient as it also need to be used for validate as well.

**Comment by aly76** [comment]
The idea of having keys in the sfdx-project.json was overturned due to security implications.
