### ISSUE TITLE
Trying to run sudo even when the agent already runs elevated (no sudo installed)

### ISSUE THREAD

**Issue by rokam** [dxatscale/sfpowerscripts#341]
**Describe the bug**
When I do run the Install commando on my pipeline at my hosted agent, I receive the following error.
> ##[error]Command failed: sudo yarn global add sfdx-cli@latest

My agent already runs on elevated user, so sudo isn't needed.

I do think that a check could be added to the  Install taks.

**To Reproduce**
1. Run the install command at an agent without sudo command.

**Expected behavior**
The sudo command in that specific case should not be fired by the task

**Platform Details (please complete the following information):**
 - OS: Ubuntu 16.04 with elevated user and no sudo
 - Version: latest
 - Salesforce Version: latest
 - CI Platform: Azure DevOps

**Comment by azlam-abdulsalam** [comment]
@rokam  we are not adding any features to azp extension as its deprecated.

https://github.com/Accenture/sfpowerscripts/discussions/322
