### ISSUE TITLE
Improve Error Message for Orchestrate.Validate

### ISSUE THREAD

**Issue by eric80shen** [dxatscale/sfpowerscripts#375]
**Describe the bug**
if no changes are made within the pkg, the pipeline validation just failed with an error message about artefact issue.
**To Reproduce**
update readme for example. and then create a PR.

**Expected behavior**
Expect validation pass or skip, not throw errors
**Screenshots**
see attached
**Platform Details (please complete the following information):**
 - CI Platform: ubutu

**Additional context**
![image](https://user-images.githubusercontent.com/17264424/107462146-8fbe6300-6baf-11eb-8d3f-a5993682a8d5.png)

**Comment by azlam-abdulsalam** [comment]
@qswh  I don't think skip is the right idea, it will still set to throw an error with the right error message
