### ISSUE TITLE
Allow SARIF as a format for PMD Analysis

### ISSUE THREAD

**Issue by jhawk-4** [dxatscale/sfpowerscripts#407]
With version [6.31.0](https://pmd.github.io/latest/pmd_release_notes_old.html#sarif-format), PMD has added support for SARIF as a report format.  Currently, `sarif` is not an allowed option for the `--format` flag in `sfdx sfpowerscripts:analyze:pmd` command.  This does work by calling the accompanying sfpowerkit command directly, but for consistency it would be good to have this in sfpowerscripts for use in CI processes.  Having the SARIF format allows [uploading the file](https://docs.github.com/en/github/finding-security-vulnerabilities-and-errors-in-your-code/uploading-a-sarif-file-to-github) to GitHub as part of a CI process.

**Comment by azlam-abdulsalam** [comment]
@manisfdcsfdx  can you get sfpowerkit to support it

**Comment by azlam-abdulsalam** [comment]
@jhawk-4  scheduled for next release

**Comment by manisfdcsfdx** [comment]
sure will do. create a issue in sfpowerkit as well https://github.com/Accenture/sfpowerkit/issues/485

**Comment by jhawk-4** [comment]
When I tested with sfpowerkit directly it generated the file in sarif format as expected as long as I used PMD version 6.31.0 or higher. I think the issue was just with sfpowerscripts, but someone is welcome to double check that.

**Comment by manisfdcsfdx** [comment]
@jhawk-4 you are right sfpowerkit accepts format as free string so when you choose 6.31.0 you can set new available format from pmd, whereas sfpowerscripts has limited the options in format. we will update powerscripts to have latest formats.

**Comment by azlam-abdulsalam** [comment]
Will be added to Release 21
