### ISSUE TITLE
Analyze PMD should provide options on when to break build

### ISSUE THREAD

**Issue by azlam-abdulsalam** [dxatscale/sfpowerscripts#432]
Analyze PMD should have options for  break build and also for warning based on options provided by a user

**Comment by rody** [comment]
In sfpowerkit, there are 2 options that can be used:
 - `--minimumpriority=minimumpriority` which sets the priority threshold
 - `--[no-]failonviolation` to activate or desactivate the failure (useful if you only want to generate a report)
