### ISSUE TITLE
Move away from using tags to compute diff

### ISSUE THREAD

**Issue by manisfdcsfdx** [dxatscale/sfpowerscripts#435]
sfpowerscripts utilise tags pushed with a particular convention on the publish stage. This is utilised by build commands for optimisation. Though its an easy solution, it has lot of flaws, such as some one accidentally deleting a tag, or pointing to the tag to a different commit or too many tags and it become noisy. To solve this, we should utilise the existing helper package (sfpowerscripts_artifact)

**Comment by azlam-abdulsalam** [comment]
@manisfdcsfdx  This will be still in RFC stage for now, as we need to deliberate as there is some logic which is based on the git data structure.
I am removing this from the roadmap temporarily
