### ISSUE TITLE
Salesforce DX 51 release is creating a problem during deployment. 

### ISSUE THREAD

**Issue by somnathdhar** [dxatscale/sfpowerscripts#443]
We have used this plugin for one of our client but as we know the latest release of Salesforce dx is causing issue during deployment. When we raised case to salesforce they advised asked to use the old version (50.0) as workaround. Since we use sfpowerscripts plugin from our Azure DevOps pipeline script so how can we control the installation of Salesforce DX version (would like to install old version)?

https://github.com/forcedotcom/cli/issues/860

**Comment by azlam-abdulsalam** [comment]
Please note sfpowerscripts azp version is deprecated and with very limited support. 

Coming back to your query, what you got from salesforce is incorrect. I would recommend you go to the latest version of sfdx-cli which Install sfdx task already does and then utilize an environment variable in a subsequent command 

sfdx force:config:set restDeploy=false

**Comment by azlam-abdulsalam** [comment]
If thats not helping, you can pass the version of the CLI in Install sfdx task such as 7.89.2 etc.

I believe you might need to look at the release notes for sfdx-cli to figure the correct version
