### ISSUE TITLE
Cutting Multiple release branches needs a manual build of all packages

### ISSUE THREAD

**Issue by azlam-abdulsalam** [dxatscale/sfpowerscripts#495]
When a new release branch is being cut from the trunk (if the user is following a trunk based development model or gitflow), sfpowerscripts will not  build any version of the package as its already built in main/master .  An earlier cut release branch would already have built some of the package and there is no need to release them at  all, though build is an activity which is relatively faster in nature, this could have issues during deployment where a full deployment of the package is not ideal. In a large org, redeploying an entire set of packages could take hours.

sfpowerscripts should provide options to the users to cut multiple release branches without the need of rebuilding all the packages

**Comment by azlam-abdulsalam** [comment]
There are two workarounds for this issue.
- Maintain a long-lived release branch and merge the trunk onto the release branch rather than cutting multiple release branches. 
or
-  When you cut the release branches, ensure there is at least one build that is building all the packages. In a subsequent commit, modify the release definition to only deploy packages that you intent to deploy for that particular release by removing it from the release definition files.

**Comment by aly76** [comment]
In the current implementation, no packages will be built when cutting a branch from a commit that was already part of a build. The workaround is to disable `--diffcheck`, so that release candidates are built, or to manually transfer release candidates into the prod feed, or update npm rc tags for single package registry.

**Comment by azlam-abdulsalam** [comment]
@aly76  I have updated the issue and associated wording to denote the current behaviour

**Comment by azlam-abdulsalam** [comment]
@aly76  I think this is not an issue and is working as expected when using a single feed. One should just use the LATEST_TAG in release definition yaml and everything should be good. Any impact on versioning should be handled by the user semantically.

In case of using multiple feeds, this has to tie into the proposal https://github.com/Accenture/sfpowerscripts/pull/500/files

If you agree with this, happy to close this one
