### ISSUE TITLE
No indication of reason after validate job deployment failure

### ISSUE THREAD

**Issue by LawrenceLoz** [dxatscale/sfpowerscripts#543]
**Describe the bug**
Failing deployments made using validate command aren't reporting the reason for failure from Salesforce in the console log

**To Reproduce**
Modify metadata so that it will trigger a deployment failure in Salesforce (e.g. reference a nonexisting field in a metadata file). I've been deploying as source packages - not sure if behaviour is same for unlocked.

**Expected behavior**
Console output should include the raw messages from Salesforce relating to the deployment failure

**Screenshots**
![image](https://user-images.githubusercontent.com/32834730/120819793-1d1e2c80-c57e-11eb-806c-c4135c78c7d1.png)

**Platform Details (please complete the following information):**
 - OS: Linux
 - Version: sfpowerscripts docker as at 3 June 2021
 - Salesforce Version: Spring '21
 - CI Platform: Github Actions

**Additional context**
I have a feeling the getFinalDeploymentStatus() function in the core package DeploySourceToOrgImpl.ts might be throwing an exception but I'm not sure

**Comment by azlam-abdulsalam** [comment]
@LawrenceLoz  this is a.bug in the sfdx cli,  you would need to use 7.103

**Comment by LawrenceLoz** [comment]
Fantastic thanks very much Azlam, I should have guessed :)

I'm upgrading sfdx-cli from the version in the docker container to 7.103.0 and confirmed this works for us now. Closing the issue assuming the container will be moved to a later release when this makes sense

**Comment by azlam-abdulsalam** [comment]
Did you face this issue with 7.101? our official one is on that

**Comment by LawrenceLoz** [comment]
Yes I'm using the official one and was getting this problem with the preinstalled 7.101

**Comment by azlam-abdulsalam** [comment]
@aly76  Can you schedule a docker release with 7.103 at the earliest

**Comment by aly76** [comment]
Latest Docker image is now on 7.104.0 of the sfdx-cli

**Comment by LawrenceLoz** [comment]
Amazing thanks both for the quick turnaround, I'll turn off our override tomorrow
