### ISSUE TITLE
No indication of reason after validate job deployment failure (reopened)

### ISSUE THREAD

**Issue by LawrenceLoz** [dxatscale/sfpowerscripts#557]
**Describe the bug**
When using an SFDX version other than the most recent, deployments which fail on validate command do not show SFDX errors and instead log exception "Unexpected token › in JSON at position 1".

This appears to be the same root cause as https://github.com/Accenture/sfpowerscripts/issues/543. Issue was addressed by updating SFDX version in the container to 7.104.0 which was the most recent at the time, but behaviour is back now that 7.105.0 is available.

**To Reproduce**

Failing scenario:
 - Initialise sfpowersripts container
 - Run validate command with metadata which fails Salesforce validation (e.g. reference a nonexisting field in a metadata file)
 - Error message as per screenshot below

Working scenario:
 - Initialise sfpowerscripts container
 - Update SFDX CLI to 7.105.0
 - Run validate command with metadata which fails Salesforce validation
 - Error message shows Salesforce-generated reason for failure as expected

**Expected behavior**
Error message from Salesforce to be surfaced in sfpowerscripts console output

**Screenshots**
![image](https://user-images.githubusercontent.com/32834730/122343373-d3ffac80-cf6f-11eb-92d0-786f67cdb645.png)

**Platform Details (please complete the following information):**
 - OS: Linux
 - Version: Version from sfpowerscripts Docker container at 17 June
 - Salesforce CLI(sfdx cli) Version: 7.104.0
 - CI Platform: Github Actions

**Comment by azlam-abdulsalam** [comment]
So 7.105 fixes it and 7.104 is broken.. it so weird how some pieces are changing in a docker image, we are missing something @aly76

**Comment by azlam-abdulsalam** [comment]
New Docker Image will be released as part of July21 solving this issue
