### ISSUE TITLE
Tag field in SfpowerscriptsArtifact is undefined 

### ISSUE THREAD

**Issue by aly76** [dxatscale/sfpowerscripts#601]
The tag field in SfpowerscriptsArtifact is undefined because git tags are no longer written to the package metadata when the packages are created by the orchestrator.

The field does not have any functional use, at the time of writing.

**Comment by azlam-abdulsalam** [comment]
Should we deprecate it?

**Comment by azlam-abdulsalam** [comment]
Will be used for future purposes, closing this issue
