### ISSUE TITLE
Azure DevOps Demo Generator references fail

### ISSUE THREAD

**Issue by vitsbruno** [dxatscale/sfpowerscripts#62]
I have already installed sfpowerscripts extension into my Azure Pipeline org, and than I tried to use Azure DevOps Demo Generator to create a sample pipeline in my org. There, I use the file https://github.com/Accenture/sfpowerscripts/releases/download/13.8000.7/sfpowerscripts_sample_pipelines.zip as a template for this sample pipeline creation. After clicking on "Create Project" button, I got this error:

"Error while creating build definition: The pipeline is not valid. A task is missing. The pipeline references a task called 'f67abc38-a5b8-4196-946e-ba81df4cd57c'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version 7.*, job 'Job_1', step 'build'.)"

Please, how can I resolve it?

**Comment by azlam-abdulsalam** [comment]
@aly76  Can you assist here? We need to update the sample pipelines

**Comment by azlam-abdulsalam** [comment]
@vitsbruno  Please use the link for the demo pipelines here 
https://github.com/Accenture/sfpowerscripts/releases/download/14.X/sfpowerscripts_sample_pipelines.zip

**Comment by vitsbruno** [comment]
It worked very well.
Thank you @azlam-abdulsalam

**Comment by noornabee-kanel** [comment]
Hello, do you have the latest link for the sample pipeline please the latest that i found did not work well
https://github.com/Accenture/sfpowerscripts/releases/download/Release_17/sfpowerscripts_sample_pipelines.zip

Regards,
Noor

**Comment by azlam-abdulsalam** [comment]
@noornabee-kanel  we have deprecated Azure Pipelines extension and no longer supporting it.  It will continue to work for existing users. please utilise the CLI and sample pipeline are available at.
https://github.com/dxatscale/easy-spaces-lwc
