### ISSUE TITLE
List Packages command

### ISSUE THREAD

**Issue by aly76** [dxatscale/sfpowerscripts#66]
**Context**
Unlike Azure DevOps, some automation platforms do not support templatization which helps with task repeatability. To mitigate this shortcoming, we propose a command that outputs the packages defined in the sfdx-project.json as an array. The array of packages can be iterated over, executing a set of tasks for each package. 

**Requirements**

- The command, by default, should list all the packages defined in the sfdx-project.json in order. 
- The command should output the list of packages as an array, omitting any packages that are defined in forceignore

**Comment by azlam-abdulsalam** [comment]
The command should also consider any override flags set in sfdx-project.json such as
- skipPMDValidation: true  (skip's  packages in the output list  when used against a PMD validation iterator)
- skipPackageValidation: true (skip's packages in the output list when used against package:valid)
- apexTestSuite: name of the apexTestSuite for the associated package

**Comment by azlam-abdulsalam** [comment]
Closing this, as it will be aligned with the consolidated task executors
