### ISSUE TITLE
CustomFieldTranslation in artifact_metadata.json causes deploysourcetoorg Task to fail

### ISSUE THREAD

**Issue by extravio** [dxatscale/sfpowerscripts#674]
**Describe the bug**
Since Friday 25 August, our pipelines have been failing. The "CustomFieldTranslation" metadata is now included in the artifact_metadata.json and it seems it's causing the deploysourcetoorg task to fail (see screenshots).

According to the [Metadata Coverage](https://developer.salesforce.com/docs/metadata-coverage) docs, "CustomFieldTranslation" is not supported in the Metadata API. Should it be included in the metadata file of the package?

**Screenshots**
![CustomFieldTranslation](https://user-images.githubusercontent.com/1171158/131269231-de7f1e4c-2ea3-46d5-a7ab-b733416058f6.PNG)
![CustomFieldTranslation-Error](https://user-images.githubusercontent.com/1171158/131269245-717813f2-9a78-4445-b6a5-deaea2639ca7.PNG)

**Platform Details (please complete the following information):**
 - OS: Ubuntu 18.04
 - Salesforce CLI(sfdx cli) Version: sfdx-cli@7.115.1 (installed with sfpwowerscript-installsfdx-task@7 )
 - CI Platform: Azure Devops sfpowerscripts extension 18.0.62 (Latest)
 - Tasks: sfpwowerscripts-createsourcepackage-task@14 / sfpowerscript-deploysourcetoorg-task@10

**Additional context**
No update has been made to the task versions. 
We've tested on a commit that had previously resulted in a successful package deployment.

**Comment by azlam-abdulsalam** [comment]
@extravio This could be an issue with sfdx cli version. Recommended to use 7.110.0 at this stage and using a docker image.

Also FYI, azure pipelines task are deprecated long time ago.  You might need to switch to the CLI
