### ISSUE TITLE
Inconsistent artifact versions in releases using NPM tags 

### ISSUE THREAD

**Issue by aly76** [dxatscale/sfpowerscripts#687]
**Describe the bug**
Release definitions with artifact versions specified using NPM tags may lead to a release where different artifact versions are installed to each org. This happens when a new artifact is published with the NPM tag, before the release has a chance to complete for every org.

**To Reproduce**

1. Define release definition using NPM tags e.g. 'main'
2. Release to Org 1
3. Build & publish new artifact with the same NPM tag
4. Release to Org 2 

**Expected behavior**
A release should be made up of a set of consistent artifact versions that are released to each org.

**Workaround**
Use `LATEST_TAG` or exact version number in release definitions. The former will only consider git tags that were created before the HEAD commit, which should be consistent in a release, across orgs.

**Comment by azlam-abdulsalam** [comment]
How would this play out during prepare command?

**Comment by azlam-abdulsalam** [comment]
@vuha-acn  Can you update docs/getting-started to signify this

**Comment by vuha-acn** [comment]
@azlam-abdulsalam - I've added it to the "Releasing to an Environment" page and the GitLab Getting Started Page for now in the dev branch for documentation.  Once I do end to end review/edits of the ADO/GitHub manuals, I'll edit them to align with GitLab as well.  Will work on a PR for the dxatscale-template for the changes.

**Comment by azlam-abdulsalam** [comment]
@aly76  We need to update sfpowerscripts doc to reflect this

**Comment by azlam-abdulsalam** [comment]
@aly76  reopening this one, as its not handled in prepare

**Comment by azlam-abdulsalam** [comment]
@vuha-acn  Need to update templates across the board, as npmTag is completely deprecated from v10.0.0

**Comment by azlam-abdulsalam** [comment]
This is fixed in December Release
