### ISSUE TITLE
Windows Issue for running sfpowerscripts commands on training

### ISSUE THREAD

**Issue by henry88lay** [dxatscale/sfpowerscripts#691]
**Describe the bug**
During DX@Scale training fellow student got an error denying using sfpowerscripts due to sfdx.ps1 cannot be loaded because running script is disabled on system.

**To Reproduce**
Run sfdx sfpowerscripts command on a work windows laptop

**Expected behavior**

**Screenshots**
![Screen Shot 2021-09-17 at 3 13 49 pm](https://user-images.githubusercontent.com/40649970/133730621-606ef3db-ee7e-4a73-a08b-bd203f89fb4f.png)

**Comment by azlam-abdulsalam** [comment]
This is not a valid issue, as its a security model with PowerShell
