### ISSUE TITLE
Using sfdx sfpowerscripts:package:data:install to recognize back slash in VlocityComponents.yaml

### ISSUE THREAD

**Issue by rubiatoEJ** [dxatscale/sfpowerscripts#692]
**Describe the bug**
`sfpowerscripts:package:data:install` won't install vlocity data packs as it recognizes back slash as an escape character when `projectPath` is inputted with back slash in `VlocityComponents.yaml `

**To Reproduce**
set projectPath in VlocityComponents.yaml same as below.. assuming vlocity data packs is already in the folder.
`projectPath: src\vlocity-config`

**Expected behavior**
If it can be recognized as part of the path and not an escape character.

**Screenshots**
![image](https://user-images.githubusercontent.com/88638065/133738041-fcec75f8-fcab-4605-ac6f-f9f1a336052b.png)

**Additional context**
Some devs do not know the difference of forward slash and back slash when commands are being executed on linux distro.

**Comment by azlam-abdulsalam** [comment]
Will be addressed as #633  goes fully live

**Comment by azlam-abdulsalam** [comment]
Handled in #633
