### ISSUE TITLE
Unable to fetch deployment failure report for Source packages with failed test classes

### ISSUE THREAD

**Issue by azlam-abdulsalam** [dxatscale/sfpowerscripts#705]
**Describe the bug**
On deployment of source packages with apex classes to a target environment and if it results in failure, sfpowerscripts is unable to display the failure

![image](https://user-images.githubusercontent.com/43767972/134597262-41f147ac-02f7-4777-8927-2da92e69d50b.png)

**To Reproduce**

1. Install a source package with test class failures to a Sandbox
2. Wait for the deployment to fail
3. Observe that no reports are published in the CI/CD logs

**Expected behavior**

sfpowerscrips should display error messages 

**Screenshots**

**Platform Details (please complete the following information):**
 - OS:  DX@Scale Docker Image
 - Version [e.g. CLI Version  eg: 1.6.6]:  8.4.0
 - Salesforce CLI(sfdx cli) Version: 7.110.0
 - CI Platform: All

** Workaround **
Login to the specific environment and check the deployment error

**Comment by dieffrei** [comment]
+1
