### ISSUE TITLE
Hard-coded user.email value in Changelog code causes git push failure

### ISSUE THREAD

**Issue by bjanderson70** [dxatscale/sfpowerscripts#710]
**Describe the bug**
Using sfpowerscript in a GitHub + Jenkins environment fails to push to the "changelog" when using _generatechangelog_

 I can release except error w/ pushing to **changeLog** ; _the internal system I am on checks the user's email (as valid)_ ... When I dug a bit deeper into this I noticed  in **changelog/ChangelogImpl.ts:pushChangelogToBranch** sets the **user.name** to "_sfpowerscripts_" and  **user.email** to "_sfpowerscripts@dxscale_" ... this is causing the failure. 

Customer runs checkemail anytime a push occurs (**not possible to disable**)

**To Reproduce**
Using the latest DockerImage . Run script (bash) in Jenkins 

_sfdx sfpowerscripts:orchestrator:release .... --generatechangelog --branchname changelog_

**Expected behavior**
Changelog with pushed release information

**Screenshots**

**Platform Details (please complete the following information):**
 - OS: Mac Big Sur 11.5.2
 - Version [e.g. CLI Version  eg: 1.6.6] What's in the current Docker image 
 - Salesforce CLI(sfdx cli) Version: [7.110.0]
 - CI Platform: GitHub + Jenkins

**Additional context**
All is fine if I do not use _--generatechangelog --branchname_

**Comment by azlam-abdulsalam** [comment]
@aly76  Lets utilise an env variable for this one?
