### ISSUE TITLE
Test Class parser doesn't detect classes with SOQL Queries UPDATE VIEWSTAT & UPDATE TRACKING

### ISSUE THREAD

**Issue by azlam-abdulsalam** [dxatscale/sfpowerscripts#724]
**Describe the bug**

sfpowerscripts is not able to detect test classes when any apex classes contain SOQL Queries that has UPDATE VIEWSTAT or UPDATE TRACKING. This will result in delayed package deployments as sfpowerscripts will attempt to deploy without optimized deployments

**To Reproduce**
1.  Utilize an apex class with a SOQL query containing UPDATE VIEWSTAT or UPDATE TRACKING
2. Create a source package
3. Deploy into a sandbox or org

**Expected behavior**

sfpowerscripts should be able to parse apex classes properly.

**Screenshots**

**Platform Details (please complete the following information):**
 - OS: All
 - Version [e.g. CLI Version  eg: 1.6.6]: 8.5.2
 - Salesforce CLI(sfdx cli) Version: 7.120.0
 - CI Platform:  N/A

**Comment by aly76** [comment]
Copying comment from closed PR for reference:

Versions 2.9.1 & 2.92 are impacted by an error on the ParseTreeWalker of Antlr4ts.
Cannot read property 'enterRule' of undefined

2.10.0 has changes to export of ApexParserListener

**Comment by azlam-abdulsalam** [comment]
Will wait for @nawforce's comments before slotting this into the release

**Comment by nawforce** [comment]
It's a bug, we have support for UPDATE VIEWSTAT and UPDATE TRACKING in SOSL but not SOQL. I will build a new version and we can take care of whatever went wrong with the ApexParserListener at the same time.

I don't know what is causing the 'Cannot read property 'enterRule' of undefined', I could really do with an example of it failing to investigate.

**Comment by aly76** [comment]
Support for UPDATE VIEWSTAT and UPDATE TRACKING in SOQL is the only outstanding issue.

We are now able to run version 2.10.0 of apex-parser, without any problems, after regenerating the package-lock files.

**Comment by nawforce** [comment]
The updates for that are done, I will publish tonight as 2.11 after doing a bit more testing.

**Comment by nawforce** [comment]
I have publish 2.11, I ran into the 'enterRule' problem while testing this so I have exported 'CommonTokenStream' & 'ParseTreeWalker' directly from apex-parser to try and reduce version confusion. To make use of this you can change the imports in ApexTypeFetcher.ts and then you don't need to directly depend on antlr4ts.

```
-import { CommonTokenStream} from "antlr4ts";
-import { ParseTreeWalker } from "antlr4ts/tree/ParseTreeWalker";
+import { CommonTokenStream} from "apex-parser";
+import { ParseTreeWalker } from "apex-parser";
```

I also got some TypeScript errors from ApexTypeListener.ts, the enter*() functions needed to be declared public to keep tsc happy.

Just as a heads up we have been working on a new Apex parser that is not based on Antlr4, it's not a direct replacement in all cases but when it can be used it will be very significantly quicker & require a lot less memory. It's not available as open source yet but hopefully that will come. I will let you know when available.

**Comment by aly76** [comment]
Thank you for your help on this one @nawforce !
Looking forward to trying out the new parser as well.
