### ISSUE TITLE
assignPermSetsPostDeployment have to be executed after postDeploymentScript

### ISSUE THREAD

**Issue by dieffrei** [dxatscale/sfpowerscripts#729]
**Describe the bug**
postDeploymentScript is executed before PermissionSet assignments.

**To Reproduce**
Try to execute any script that requires permission set assignment before postDeploymentScript.

**Expected behavior**
Execute first permission set assignments then execute postDeploymentScript

**Comment by azlam-abdulsalam** [comment]
Thanks @dieffrei  I am refactoring this area and have noticed it. Stay tuned
