### ISSUE TITLE
Error when post deployment script in Bitbucket

### ISSUE THREAD

**Issue by gretarvp** [dxatscale/sfpowerscripts#745]
**Describe the bug**
When our post-deployment script is run in our Bitbucket pipeline we get the following error:

Error: 
/bin/sh: bash: not found

**To Reproduce**
1. Add the following to the sfdx-project.json
`
        {
            "path": "./testdata",
            "package": "TestData",
            "versionNumber": "1.0.0.0",
            "type": "data",
            "postDeploymentScript": "scripts/bitbucket/dataPostDeployment.sh",
            "skipDeployOnOrgs": [
                "qa",
                "staging",
                "prod"
            ]            
        }`

**Expected behavior**
The scripts/bitbucket/dataPostDeployment.sh runs successfully like it does when run locally.

**Desktop (please complete the following information):**

- OS: Windows 10
- Node Version
- Version of sfpowerkit[e.g 1.45.0]: @dxatscale/sfpowerscripts 8.4.0
- Salesforce Org Version [ In case of pre release window ]

**Comment by azlam-abdulsalam** [comment]
@gretarvp Whats your OS in bitbucket? if its windows you need batch file, and fyi we test sfpowerscripts only on Ubuntu as its more to be run on a CI server

**Comment by gretarvp** [comment]
@azlam-abdulsalam Our OS in Bitbucket is an Alpine Linux - our container uses node:current-alpine https://hub.docker.com/layers/node/library/node/current-alpine/images/sha256-2b23ebc268505a03d191bff042309d73d559e86f78c0a71777e00bad3acbbf90?context=explore
as a base image.

We're installing a few apps on top of that distro, to build our image.  Do you need more info related to this issue?

**Comment by azlam-abdulsalam** [comment]
@gretarvp  probably something we need to fix, we are triggering the script using bash and bash may not be available in the image. We should use shell instead

https://github.com/Accenture/sfpowerscripts/blob/develop/packages/core/src/package/packageInstallers/PackageInstallationHelpers.ts

**Comment by azlam-abdulsalam** [comment]
@aly76  can you have a look into this one? do we have any specific requirement for bash

**Comment by gretarvp** [comment]
For your info, we were able to make the script work in Bitbucket by adding bash to our docker image but it will help to make the default shell work as well.
