### ISSUE TITLE
Prevent to update packages versions already promoted

### ISSUE THREAD

**Issue by dieffrei** [dxatscale/sfpowerscripts#783]
Often developers forget to bump the package version, which causes a lot of release pipeline builds failures.

sfdx sfpowerscripts:orchestrator:validate command should check if any package related to the changes, can be promoted or if now it should fail, and request developer to bump package since it was already promoted in devhub

**Comment by azlam-abdulsalam** [comment]
This feature is delivered in sfops, removing from sfpowerscripts
