### ISSUE TITLE
orchestrator:prepare with enableSourceTracking throws File not found error

### ISSUE THREAD

**Issue by sbresin** [dxatscale/sfpowerscripts#789]
**Describe the bug**
When preparing a scratchOrg pool using orchestrator:prepare it throws an error because of a missing `maxRevision.json` inside the `.sfpowerscripts/sourceTrackingFiles/` folder.
```
Deploying all packages in the repo to  SO1
Failed to execute scripts for test-bkicqn22ulvy@example.com with alias SO2 due to File not found: .sfpowerscripts/sourceTrackingFiles/test-bkicqn22ulvy@example.com/maxRevision.json
Succesfully deleted scratchorg  test-bkicqn22ulvy@example.com
```
I used this this pool config:
```
{
    "$schema": "https://raw.githubusercontent.com/Accenture/sfpowerscripts/develop/packages/sfpowerscripts-cli/resources/schemas/pooldefinition.schema.json",
    "tag": "dev",
    "maxAllocation": 1,
    "expiry": 10,
    "batchSize": 5,
    "configFilePath": "config/project-scratch-def.json",
    "relaxAllIPRanges": true,
    "installAll": true,
    "enableSourceTracking": true,
    "retryOnFailure": true,
    "succeedOnDeploymentErrors": true
}
```

**To Reproduce**

1. set `"installAll": true` and `"enableSourceTracking": true` in your pool config
2. run `sfdx sfpowerscripts:orchestrator:prepare -f config/project-dev-pool-def.json -v devhub`

**Expected behavior**
Source Tracking Static Resource should get created.

**Platform Details (please complete the following information):**
 - OS: macOS 12.0.1
 - Version [e.g. CLI Version  eg: 1.6.6]: tried v10.2.3 and develop branch
 - Salesforce CLI(sfdx cli) Version: sfdx-cli/7.129.0 darwin-x64 node-v16.13.0

**Comment by azlam-abdulsalam** [comment]
@sbresin Is there any issues while you do a normal source push? Also can you provide the logs from . sfpowerscripts/prepare_logs

**Comment by sbresin** [comment]
@azlam-abdulsalam thanks for the hint!

I didn't check this log properly and i had indeed some conflicting metadata.
So everything is right with sfpowerscripts. Just the error message is a little misleading.

Thanks for the great tool, i'll close the issue :)
