### ISSUE TITLE
Building error with PlatformEventSubscriberConfig

### ISSUE THREAD

**Issue by DanielCalle** [dxatscale/sfpowerscripts#810]
**Describe the bug**
When I use the dxatscale/sfpowerscripts:latest docker image, the version of sfpowerscripts it contains throws an error when building an artifact with PlatformEventSubscriberConfig metadata type.

**To Reproduce**
Create a package with a metadata of type PlatformEventSubscriberConfig and run 'sfdx sfpowerscripts:orchestrator:quickbuild --diffcheck --loglevel debug --branch $(git rev-parse --abbrev-ref HEAD) '

**Expected behavior**
The package should be created correctly with the "release-aug21" version works fine.

**Screenshots**
![image](https://user-images.githubusercontent.com/11243437/149835596-88f875bb-f00c-4a1f-9039-016f75b3e784.png)

**Platform Details (please complete the following information):**
 - OS: Ubuntu
 - Version: 10.2.6 -Release:December 21
 - Salesforce CLI(sfdx cli) Version: 7.129.0
 - CI Platform: Azure DevOps

**Comment by azlam-abdulsalam** [comment]
@DanielCalle  This is since recent versions of SFDX CLI are strict with incorrect placement of metadata, Can you check the metadata is placed correctly in the correct parent folder?

**Comment by DanielCalle** [comment]
@azlam-abdulsalam I performed the same run with quickbuild updating both **sfdx** and **sfpowerscripts** locally and it worked fine too.

The versions I tested locally are:
sfdx-cli/7.133.0 linux-x64 node-v16.13.1
sfpowerscripts -- The DX@Scale CI/CD Orchestrator -Version:10.2.6 -Release:December 21

The metadata path for this package is as follows:
`src/env-specific/int/main/PlatformEventSubscriberConfigs/CI_ConsumerRequestEventTriggerConfig.platformEventSubscriberConfig-meta.xml`
`src/env-specific/uat/main/PlatformEventSubscriberConfigs/CI_ConsumerRequestEventTriggerConfig.platformEventSubscriberConfig-meta.xml`
`src/env-specific/pro/main/PlatformEventSubscriberConfigs/CI_ConsumerRequestEventTriggerConfig.platformEventSubscriberConfig-meta.xml`

The package configuration in sfdx-project is:
```
    {
      "path": "src/env-specific",
      "aliasfy": true,
      "default": false,
      "package": "src-env-specific",
      "versionNumber": "1.0.1"
    }
```

**Comment by azlam-abdulsalam** [comment]
I see, looks like  this is a bug with 7.129.0 version of the cli.  We will update it as part of the next release.

**Comment by azlam-abdulsalam** [comment]
Will be part of February 2022 update
