### ISSUE TITLE
orchestrator:prepare fails in GitLab Cloud Runners during SO Pool for updated artifact versions

### ISSUE THREAD

**Issue by vuha-acn** [dxatscale/sfpowerscripts#811]
**Describe the bug**
During Prepare SO Pool Creation in GitLab Cloud, when all artifacts are generated the first time, the Scratch Org Pools are successfully created with all the artifacts.  Once 1 artifact is changed and updated to a new version (latest), the SO Pool Creation fails (see UI errors and log file errors).  

**To Reproduce**

1. In GitLab Cloud, set up project-template with dxatscale-template for GitLabs
2. Generate all artifacts for the first time.
3. Run prepare commands and create SO Pool.
4. Success
4. Update 1 artifact. Re-run SO prepare commands.
5. Failure
6. Update all artifacts. Re-run SO prepare commands.
7. Success

**Expected behavior**

SO Prepare Pools should be able to work consistently in GitLab Cloud runners.  

**Screenshots**

Failed to execute scripts for test-8lnkub6usu3w@example.com with alias SO5 due to File not found: .sfpowerscripts/sourceTrackingFiles/test-8lnkub6usu3w@example.com/maxRevision.json

![image](https://user-images.githubusercontent.com/59901319/149843531-834f8725-f5bb-45d0-bbd9-c75c2b29090d.png)

_SO prepare_logs_

Deploying all packages in the repo to  SO5
Error: Artifacts must originate from the same source repository, for deployment to work
Cancelling any further packages to be deployed, Adding the scratchorg SO5 to the pool

**Platform Details (please complete the following information):**
 - OS: [GitLab.com Shared Runners](https://docs.gitlab.com/runner/#runners-on-gitlabcom)  
 - Version [e.g. CLI Version  eg: 1.6.6]  - Latest
 - Salesforce CLI(sfdx cli) Version: sfdx-cli@7.129.0
 - CI Platform: GitLab.com

**Additional context**
Error message in the UI and Logs should be consistent to avoid confusion. (eg. maxRevision.json vs. Artifacts must originate from the same source repository)

Review regex options to filter out dynamic URL from GitLab Runners 

- git remote set-url --push origin https://gitlab-ci-token:${PROJECT_ACCESS_TOKEN}@$CI_SERVER_HOST/$CI_PROJECT_PATH.git

"repository": "https://gitlab-ci-token:ABC123xyz@gitlab.com/organization/dxatscale-template-sample-project.git"

gitlab-ci-token:ABC123xyz Token is generated differently for each new artifact build for the pipeline.

**Comment by azlam-abdulsalam** [comment]
Fixed in 10.2.7
