### ISSUE TITLE
orchestrator deploy ignores alwaysDeploy flag

### ISSUE THREAD

**Issue by ppeers** [dxatscale/sfpowerscripts#829]
In version 10.0.2.5 a bug was fixed for sfpowerscripts:orchestrator:release, so that it works with a combination of skipIfAlreadyInstalled and alwaysDeploy (when alwaysDeploy = true the package should always be installed on release, even though skipIfAlreadyInstalled = true). But now we see that sfpowerscripts:orchestrator:deploy ignores the alwaysDeploy flag (even when the flag is set to true, the package is only deployed when the version is bumped).

**Comment by azlam-abdulsalam** [comment]
@ppeers   Can you confirm whether the package is built? deploy command only deploys if the artifact is available.

**Comment by azlam-abdulsalam** [comment]
@ppeers  Please reopen if the response is not satisfactory
