### ISSUE TITLE
Failed to delete scratch org after validation

### ISSUE THREAD

**Issue by rubiatoEJ** [dxatscale/sfpowerscripts#838]
**Describe the bug**
When a PR validation is failed, an error also occurs that is unable to delete the scratch org.

When PR validation is successful, the deletion of scratch org after the run is successful as well.

I have checked this on every PR starting yesterday as the unusual error started yesterday, I noticed that it only occurs when a PR validation is failed.

I have attached the full raw logs as well.

[Failed PR Validation (failed to delete scratchorg after validation).txt](https://github.com/Accenture/sfpowerscripts/files/8046177/Failed.PR.Validation.failed.to.delete.scratchorg.after.validation.txt)
[Successful PR Validation (successful deletion of scratchorg after validation).txt](https://github.com/Accenture/sfpowerscripts/files/8046178/Successful.PR.Validation.successful.deletion.of.scratchorg.after.validation.txt)

**To Reproduce**
- Run a validation that will success using the sfpowerscripts:orchestrator:validate
- Run a validation that will fail using the sfpowerscripts:orchestrator:validate

**Expected behavior**
When a PR validation is failed the deletion of scratch should not fail as well.

**Screenshots**
Failed PR validation:
![image](https://user-images.githubusercontent.com/88638065/153543668-739c268f-fb93-40e7-a7bc-916aa917c4b5.png)

Successful PR validation:
![image](https://user-images.githubusercontent.com/88638065/153386439-077ded54-946d-48d8-a331-415817f0a18a.png)

**Platform Details (please complete the following information):**
 - OS: 
 - Version [e.g. CLI Version  eg: 1.6.6]: 10.2.13
 - Salesforce CLI(sfdx cli) Version: 
 - CI Platform: Github

**Additional context**

**Comment by azlam-abdulsalam** [comment]
@rubiatoEJ  It could be a erroneous log, Can you confirm whether the org is active in DevHub?

**Comment by thvd** [comment]
@azlam-abdulsalam  we are seeing the same thing, a scratch org taken from the pool cannot be deleted, seeing the same error here. Use latest SFDX CLI version

**Comment by rubiatoEJ** [comment]
> @rubiatoEJ It could be a erroneous log, Can you confirm whether the org is active in DevHub?

@azlam-abdulsalam I have checked a latest failed PR validation as the previous org has already expired.

this is the latest failed PR validation and failed to delete the scratch org

I have asked to check if the org is active in DevHub and it shows as active
![image](https://user-images.githubusercontent.com/88638065/153543558-25584f6c-baa5-4c1e-b98f-db38db58ba2d.png)

**Comment by azlam-abdulsalam** [comment]
Folks, this will need further investigation, as something with sfdx-cli 7.136.2 has changed. We advise all of you to rollback into `release-dec21` docker image  or 7.129.0 until we figure out a work around.

**Comment by azlam-abdulsalam** [comment]
@thvd @rubiatoEJ  do you have the same issue with orgs fetched from developer pool? Locally everything works. :(

**Comment by azlam-abdulsalam** [comment]
@mshanemc any ideas here?

**Comment by rubiatoEJ** [comment]
> @thvd @rubiatoEJ do you have the same issue with orgs fetched from developer pool? Locally everything works. :(

@azlam-abdulsalam I have tried fetching from developer pool and delete with the same command used in validate
![image](https://user-images.githubusercontent.com/88638065/153558882-fb85999c-9bc0-4c6e-93b5-8e59966b84ce.png)

and it shows that it is successfully deleted.

Additional info:
sfdx-cli version used is below:
`$ sfdx --version`
`sfdx-cli/7.129.0 win32-x64 node-v16.13.0`

**Comment by azlam-abdulsalam** [comment]
@aly76  I cant reproduce this locally, so it happens in docker image only. Probably the auth file is written to a plugin space?

**Comment by rubiatoEJ** [comment]
Updated the `sfdx-cli` to the latest version and tried to delete the org again but it is still successful

![image](https://user-images.githubusercontent.com/88638065/153561666-e4e8dcf6-ba62-40fa-8cae-3a73942fc36a.png)

`$ sfdx --version`
`sfdx-cli/7.137.1 win32-x64 node-v16.13.0`

**Comment by sumanth-bolledla-acn** [comment]
I'm able to reproduce this as well, attaching screenshot here
<img width="455" alt="s0-deletion-failure" src="https://user-images.githubusercontent.com/92749436/153621738-d46d3068-54e5-4d5d-8b94-c691938d2d5a.png">

**Comment by azlam-abdulsalam** [comment]
Fixed in 10.2.15
