### ISSUE TITLE
Orchestrator should ignore packageDirectories without a "package" attribute

### ISSUE THREAD

**Issue by rody** [dxatscale/sfpowerscripts#842]
Orchestrator requires all `packageDirectories` in the `sfdx-project.json` to be declared as packages (i.e. it requires `package` and `versionNumber` attributes).

Salesforce DX allows to declare directories that are not packages. This is quite useful when you want to have a specific path for the metadata that you pull from a Scratch Org.

**To Reproduce**
Add the following to the `packageDirectories` in `sfdx-project.json`:

```json
{
  "path": "tmp",
  "default": true
}
```

and run `sfdx sfpowerscripts:orchestrator:build`

It results in the following error
```
ERROR running sfpowerscripts:orchestrator:build:  The sfdx-project.json is invalid, Please fix the following errors

1: /packageDirectories/2: must have required property 'package' {
    "missingProperty": "package"
}
2: /packageDirectories/2: must have required property 'versionNumber' {
    "missingProperty": "versionNumber"
```

**Expected behavior**
The `tmp` packageDirectory is ignored from the list of packages to create (because it does not have a `package` or `versionNumber` attribute). The other packages are built.
Optionally a info message could be displayed saying that the directory is ignored because it's not a package.

_Implementation note_: If `package` is present but not `versionNumber` (and vice-versa), then sfpowerscripts should fail with an error message, since the package definition is incomplete.

**Comment by azlam-abdulsalam** [comment]
Thanks @rody  for raising this. Will try to add this as part of April's release
