### ISSUE TITLE
Unable to fetch scratch org from dev pool

### ISSUE THREAD

**Issue by rubiatoEJ** [dxatscale/sfpowerscripts#848]
**Describe the bug**
When running `sfpowerscripts:pool:fetch` command, some of us are unable to fetch and encountering this error message:
`ERROR running sfpowerscripts:pool:fetch:  No scratch org available at the moment for dev, try again in sometime.`

It is somehow weird that some us are able to fetch a scratch org from dev pool.
I have also tried fetching scratch org from CI pool and still unable to fetch.
We have also asked to double check our permissions in devhub but nothing was modified or changed and everyone has the same permission.

**To Reproduce**
Prepare a scratch orgs in the pool, either dev or ci and authenticate to devhub.
After successful preparation, run `sfdx sfpowerscripts:pool:fetch`
(e.g.) `sfdx sfpowerscripts:pool:fetch -t dev -a SO-test -v devhub`

**Expected behavior**
Should be able to successfully fetch a scratch org from pool.

**Screenshots**
![image](https://user-images.githubusercontent.com/88638065/154877386-cfdd913e-2411-4f22-8d4a-37c2c020f6e6.png)

**Platform Details (please complete the following information):**
 - OS: 
 - Version [e.g. CLI Version  eg: 1.6.6]
   -     @dxatscale/sfpowerscripts 10.2.13
          sfdmu 4.12.7
          sfdx-browserforce-plugin 2.8.0
          sfpowerkit 4.1.5
            
 - Salesforce CLI(sfdx cli) Version: sfdx-cli/7.137.1
 - CI Platform: 

**Additional context**

In latest Replenish of DEV pool, the replenishment is successful
![image](https://user-images.githubusercontent.com/88638065/154880953-5c5ce827-7580-4b2a-b160-2190dfd51e9c.png)

**Comment by rubiatoEJ** [comment]
Would like to ask help for further analysis / investigation.

**Comment by azlam-abdulsalam** [comment]
please provide sfpowerscripts version which is having this issue vs others

**Comment by azlam-abdulsalam** [comment]
As discussed closing this, as its an issue with sharing rules
