### ISSUE TITLE
Utilize Salesforce CLI hooks for pre and post deployment scripts

### ISSUE THREAD

**Issue by pelim** [dxatscale/sfpowerscripts#853]
## Utilize Salesforce CLI hooks for pre and post-deployment scripts 

> https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_plugins.meta/sfdx_cli_plugins/cli_plugins_customize_hooks_steps.htm

**Implement generic cli hook that allows custom javascript hooks for each source package**

- match HookOptions.argv[] "-f .*" == "current package dir"
- allow implementation per metadata type ```NamedCredential.hook.js```

**Example Predeployment Hook**

```javascript
class NamedCredentialHook extends PredeploymentHook {
  
  const datasourceCredentials = Credentials.fromDatasource({
     path: "./config/credential-storage.enc"
  }, env.CI_CREDENTIAL_MASTER_PASSWORD);

  async function exec(data) {
    datasourceCredentials.findEntriesByProperty('identifier', data.fullName).then((entry) {
      data.endpoint = entry.getProperty('endpoint');
      data.username = entry.getProperty('username');
      data.password = entry.getProperty('password');

      return data;
    });    
  }
}

```

**Comment by azlam-abdulsalam** [comment]
Closing this issue for now, will revisit it later
