### ISSUE TITLE
Fail to fetch requested information when query is too long

### ISSUE THREAD

**Issue by azlam-abdulsalam** [dxatscale/sfpowerscripts#860]
**Describe the bug**

sfpowerscripts when used in large brownfield projects in the process of refactoring, fails to process queries that operate on larger collection of entities, resulting in salesforce throwing   ```<h1>Bad Message 414</h1><pre>reason: URI Too Long</pre>```

**To Reproduce**

1. Utilize a package that has large number of apex classes and the overall length of collection as a string is more than 12k characters
2. Notice the commands throw exception.

**Expected behavior**

sfpowerscripts should retrieve results in chunks and merge it together. 

**Screenshots**

**Platform Details (please complete the following information):**
 - OS:  All
 - Version [e.g. CLI Version  eg: 1.6.6] : 10.2.15
 - Salesforce CLI(sfdx cli) Version: 7.136.2
 - CI Platform:  All

**Additional context**

**Comment by azlam-abdulsalam** [comment]
Thanks to @rocko1204 for bringing this to our attention and sharing the patch used 
[Patch2.txt](https://github.com/Accenture/sfpowerscripts/files/8128519/Patch2.txt)

**Comment by aly76** [comment]
URI length has a maximum length of 16,057 chars, and the WHERE clause has a maximum length of 4000 chars

https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_select_conditionexpression.htm

**Comment by aly76** [comment]
https://developer.salesforce.com/docs/atlas.en-us.236.0.salesforce_app_limits_cheatsheet.meta/salesforce_app_limits_cheatsheet/salesforce_app_limits_platform_soslsoql.htm
