### ISSUE TITLE
Optional mode for deploying only changed components when installing a source package

### ISSUE THREAD

**Issue by azlam-abdulsalam** [dxatscale/sfpowerscripts#862]
Deployment of source packages can be optimized by only doing a deployment of changed components.  These components should be recorded in the artifact by basis of version history (like ancestors in managed packages). This provides an optimal deployment and negates any issues with an artifact created by using git-based delta.

During deployment, depending on the version that is installed in the target org, an aggregation of changed components will be computed and deployed to the org. In case of any issues in computing the changed component, it should fall back to the full package deployment.

**Comment by vuha-acn** [comment]
In an ideal situation, the source packages would be smaller and the delta deployments would not make a big difference in timings.  For new adopters for modular development that have 300+ metadata in their packages, this would be a good feature to have as they continue to re-factor and reduce the volume of metadata in the source package.

**Comment by azlam-abdulsalam** [comment]
Closing this issue, as its not worth the engineering efforts at this stage, One can use diff packages while they refactor to small source packages .
