### ISSUE TITLE
GitHub NPM sfdx sfpowerscripts:orchestrator:publish fails

### ISSUE THREAD

**Issue by Schuchie** [dxatscale/sfpowerscripts#886]
**Describe the bug**
I copied your GitHub [Template](https://github.com/dxatscale/dxatscale-template) for a CI and followed your [guide](https://docs.dxatscale.io/ci-cd/reference-implementation/github/getting-started).
I have also set up all the Secrets so far. The actions can connect to the respective orgs. However, as soon as an NPM package should be published, the following problem occurs.
Following action fails: "CI Pipeline - Auto Triggered"
We also got the GitHub-Team License.

**To Reproduce**

1. Follow your guide and setup the pipeline.
2. Trigger the pipeline via a push to the main branch.

**Expected behavior**
Package gets published to NPM.

**Platform Details (please complete the following information):**
 - OS: Current runner version: '2.288.1'
 - Version -
 - Salesforce CLI(sfdx cli) Version: -
 - CI Platform: GitHub Actions

**Additional context**
Action Log:
```
sfdx sfpowerscripts:orchestrator:publish -d artifacts --npm --scope @ValanticDMC  --gittag --pushgittag
  shell: sh -e {0}
-------------------------------------------------------------------------------------------
sfpowerscripts  -- The DX@Scale CI/CD Orchestrator -Version:10.2.15 -Release:February 22
-------------------------------------------------------------------------------------------
command: publish
target: NPM
Publish promoted artifacts only: false
-------------------------------------------------------------------------------------------
Publishing core Version 1.0.0-19561[3](https://github.com/ValanticDMC/SF-Deployment/runs/5477156894?check_suite_focus=true#step:8:3)9065 with tag main...
Command failed: npm publish --tag main
npm notice 
npm notice package: @valanticdmc/core_sfpowerscripts_artifact@1.0.0-1956139065
npm notice === Tarball Contents === 
npm notice 670B  source/forceignores/.buildignore                                                       
npm notice 670B  source/.forceignore                                                                    
npm notice 670B  source/forceignores/.prepareignore                                                     
npm notice 670B  source/forceignores/.quickbuildignore                                                  
npm notice 670B  source/forceignores/.validateignore                                                    
npm notice 857B  artifact_metadata.json                                                                 
npm notice 263B  changelog.json                                                                         
npm notice 160B  package.json                                                                           
npm notice 258B  source/sfdx-project.json                                                               
npm notice 88B   source/src/core-crm/README.md                                                          
npm notice 2.[4](https://github.com/ValanticDMC/SF-Deployment/runs/5477156894?check_suite_focus=true#step:8:4)kB source/manifests/sfdx-project.json.ori                                                 
npm notice 481B  source/src/core-crm/main/default/objects/Account/fields/AccountNumber__c.field-meta.xml
npm notice === Tarball Details === 
npm notice name:          @valanticdmc/core_sfpowerscripts_artifact
npm notice version:       1.0.0-19[5](https://github.com/ValanticDMC/SF-Deployment/runs/5477156894?check_suite_focus=true#step:8:5)[6](https://github.com/ValanticDMC/SF-Deployment/runs/5477156894?check_suite_focus=true#step:8:6)139065                         
npm notice package size:  2.0 kB                                   
npm notice unpacked size: [7](https://github.com/ValanticDMC/SF-Deployment/runs/5477156894?check_suite_focus=true#step:8:7).[8](https://github.com/ValanticDMC/SF-Deployment/runs/5477156894?check_suite_focus=true#step:8:8) kB                                   
npm notice shasum:        0[9](https://github.com/ValanticDMC/SF-Deployment/runs/5477156894?check_suite_focus=true#step:8:9)b2f07063981f5e36870182081a8940d94b5c84 
npm notice integrity:     sha5[12](https://github.com/ValanticDMC/SF-Deployment/runs/5477156894?check_suite_focus=true#step:8:12)-CwUnYHBeVXWeo[...]4lINQ2P5WbQEg== 
npm notice total files:   12                                       
npm notice 
npm ERR! code E404
npm ERR! 404 Not Found - PUT https://registry.npmjs.org/@valanticdmc%2fcore_sfpowerscripts_artifact - Not found
npm ERR! 404 
npm ERR! 404  '@valanticdmc/core_sfpowerscripts_artifact@1.0.0-1956[13](https://github.com/ValanticDMC/SF-Deployment/runs/5477156894?check_suite_focus=true#step:8:13)9065' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /github/home/.npm/_logs/2022-03-09T08_34_25_294Z-debug.log

----------------------------------------------------------------------------------------------------
0 artifacts published in 00:00:01 with {1} errors
Packages Failed to Publish core v1.0.0-[19](https://github.com/ValanticDMC/SF-Deployment/runs/5477156894?check_suite_focus=true#step:8:19)561[39](https://github.com/ValanticDMC/SF-Deployment/runs/5477156894?check_suite_focus=true#step:8:39)065
----------------------------------------------------------------------------------------------------
Error: Process completed with exit code 1.
```

**Comment by azlam-abdulsalam** [comment]
@Schuchie  Can you follow the discussion here
https://github.com/Accenture/sfpowerscripts/discussions/792

@henry88lay  @ramesh-karanji Lets have a look into this and close it for good

**Comment by ramesh-karanji** [comment]
@Schuchie I have re-tested our GitHub templates for build and publish, it worked fine on my repo without any errors to publish. 

![image](https://user-images.githubusercontent.com/45953913/157583491-2157a8b3-3424-4ebb-8a67-35ebfd03c686.png)

Please check the workflow permissions under the repo settings -> actions > general > workflow permissions check "read and write permissions" option is selected, this plays a key role as GITHUB_TOKEN gets required level of access to publish packages. In some cases at Org level permissions will be restricted by admins for GITHHUB_TOKEN.

Read: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token

However, if you still find issues there is another option which is through your PAT with appropriate permissions are selected while generating token

@azlam-abdulsalam  @henry88lay

**Comment by Schuchie** [comment]
Hey @azlam-abdulsalam ,

we have the same settings as you have. The token gets correct used in the pipeline. The GitHub-Author-Variable looks like to be the problem. 

Could it be that our github company name is in uppercase and lowercase?

**Comment by Schuchie** [comment]
Short update: I tested it, If the GitHub-Author contains upper and lower cases GitHub-Author-Variable does not work for your template. If you hardcode the name it works.

**Comment by azlam-abdulsalam** [comment]
Thanks @Schuchie  have you come around any workaround which uses variables? 

@henry88lay @ramesh-karanji fyi

**Comment by Schuchie** [comment]
@azlam-abdulsalam 
You could define an own env-variable with an hardcoded lowercase github name. This would work, currently I hardcoded it everywhere (without a var):D

**Comment by azlam-abdulsalam** [comment]
The template is updated to address this using setup node
