### ISSUE TITLE
Replenish DEV Pools - Auto Triggered FAILED (SourceTracking issue)

### ISSUE THREAD

**Issue by nufonsec-kz** [dxatscale/sfpowerscripts#889]
**Describe the bug**
When i try to run the Replenish DEV Pools - Auto Triggered it's falling saying that "_Failed to execute scripts for test-vzpfcx58oql4@example.com with alias SO5 due to File not found: .sfpowerscripts/sourceTrackingFiles/test-vzpfcx58oql4@example.com/maxRevision.json_"
For the Replenish CI Pools all works fine

**To Reproduce**
I've copied your template
Followed all the steps in the guide
Github Actions is connecting to Dev Hub
Manually trigger the Action **Replenish DEV Pools**

**Expected behavior**
Creation and Allocation of Scratch Orgs to Dev Pool

**Screenshots**
Deploying all packages in the repo to  SO2
Installing Package Dependencies of this repo in SO4
Successfully completed Installing Package Dependencies of this repo in SO4
Deploying all packages in the repo to  SO4
Failed to execute scripts for test-vzpfcx58oql4@example.com with alias SO5 due to File not found: .sfpowerscripts/sourceTrackingFiles/test-vzpfcx58oql4@example.com/maxRevision.json
Succesfully deleted scratchorg  test-vzpfcx58oql4@example.com
Failed to execute scripts for test-lgdqqebffvcy@example.com with alias SO4 due to File not found: .sfpowerscripts/sourceTrackingFiles/test-lgdqqebffvcy@example.com/maxRevision.json
Succesfully deleted scratchorg  test-lgdqqebffvcy@example.com
Failed to execute scripts for test-sy3ishj2yjcn@example.com with alias SO3 due to File not found: .sfpowerscripts/sourceTrackingFiles/test-sy3ishj2yjcn@example.com/maxRevision.json
Succesfully deleted scratchorg  test-sy3ishj2yjcn@example.com
Failed to execute scripts for test-vs3lbnlzdpf7@example.com with alias SO2 due to File not found: .sfpowerscripts/sourceTrackingFiles/test-vs3lbnlzdpf7@example.com/maxRevision.json
Succesfully deleted scratchorg  test-vs3lbnlzdpf7@example.com
Failed to execute scripts for test-l3yjhdhifiow@example.com with alias SO1 due to File not found: .sfpowerscripts/sourceTrackingFiles/test-l3yjhdhifiow@example.com/maxRevision.json
Succesfully deleted scratchorg  test-l3yjhdhifiow@example.com
-----------------------------------------------------------------------------------------------------------
All requested scratch orgs failed to provision, Please check your code or config
-----------------------------------------------------------------------------------------------------------
Error: Process completed with exit code 1.

**Platform Details (please complete the following information):**
 - OS: 
 - Version [e.g. CLI Version  eg: 1.6.6]
 - Salesforce CLI(sfdx cli) Version: 
 - CI Platform: Github Actions

**Additional context**
I've changed the flag **enableSourceTracking** to false in the _project-dev-pool-def.json_ file and Scratch Orgs were created and allocated without any issues

**Comment by azlam-abdulsalam** [comment]
Can you provide the prepare logs file which will show what happened.

**Comment by nufonsec-kz** [comment]
Hi @azlam-abdulsalam here is the zip file
[logs_2.zip](https://github.com/Accenture/sfpowerscripts/files/8323826/logs_2.zip)
.

**Comment by azlam-abdulsalam** [comment]
@nufonsec-kz  Looked at the logs, can you confirm the packages are published

2022-03-21T17:03:16.1278672Z [95m[1mValidating Org Authentication Mechanism..[22m[39m
2022-03-21T17:03:18.2304578Z [93mGit Tag for core missing, This might result in deployment failures[39m
2

**Comment by nufonsec-kz** [comment]
Hi Azlam,

Yes, the packages are published. I followed all the instructions from the
docs and I did it before without any issues, only now in a new installation
i'm facing this issue.

Regards
*Nuno Fonseca*
Managing Director - Head of Architecture
Mobile: +351 963 054 576
E-mail: ***@***.***
<http://www.kompetenza.com>

**Comment by azlam-abdulsalam** [comment]
@nufonsec-kz  Could this be related to this? The authentication to npm might be failing
https://github.com/Accenture/sfpowerscripts/issues/886

**Comment by nufonsec-kz** [comment]
@azlam-abdulsalam authentication to npm looks ok. I just checked and my personal token was expired, i generated a new one and still have the same issue.

**Comment by azlam-abdulsalam** [comment]
@nufonsec-kz  Hit us in the slack channel, so we could look into this further

**Comment by azlam-abdulsalam** [comment]
Closing this, as it addressed in the updates to GitHub template
