### ISSUE TITLE
Authenticate Using Credentials - Error Parsing ")" if contained in password

### ISSUE THREAD

**Issue by vuha-acn** [dxatscale/sfpowerscripts#89]
When executing the authentication task, if there is a ")" in the password for credential authentication, the task fails.  

**Error Message:**

1: Syntax error: ")" unexpected

**Sample Command Output:**

##[error]Command failed: sfdx sfpowerkit:auth:login -u user_name@salesforce.com -p pass)word -s aDFE3342432VDddeere33111 -a sampleAlias

**Comment by Caitlyn-Mills** [comment]
Thank you for raising an issue with sfpowerscripts. This problem can be solved by encapsulating the password in quotation marks. eg: 
sfdx sfpowerkit:auth:login -u user_name@salesforce.com -p "pass)word" -s aDFE3342432VDddeere33111 -a sampleAlias
