### ISSUE TITLE
src-env-specific for scratch orgs possible?

### ISSUE THREAD

**Issue by Schuchie** [dxatscale/sfpowerscripts#891]
**Describe the question to doc**
Its not a bug, but I did not found any documentation to it: Is there way to define "src-env-specific" metadata for all scratch orgs?
Its relevant for audiences which are needed for a community cloud/digital experience site with a variation navigation.
You can't push/deploy a default audience without any criteria to scratch orgs, but to sandboxes (its a sf bug). Sandboxes cant have a criteria in a default audience. The workaround would be to have different Default Audience's for scratch orgs and the sandboxes.

https://dxatscale.gitbook.io/sfpowerscripts/faq/package-types/source-packages#what-are-my-options-with-source-packages

**Comment by azlam-abdulsalam** [comment]
you can put it in the default folder, check here
https://github.com/Accenture/sfpowerscripts/blob/develop/decision%20records/deployments/001-aliasified-data-sourcepackages.md
