### ISSUE TITLE
Pool Fetch Error / TypeError: Cannot read properties of undefined (reading 'bold')

### ISSUE THREAD

**Issue by ozanbotanls** [dxatscale/sfpowerscripts#892]
**Describe the bug**

When running the pool:fetch command from within the integrated terminal, started to get the following error message 
`TypeError: Cannot read properties of undefined (reading 'bold')`

**To Reproduce**

1. Make sure you have scratches in the pool
2. `sfdx sfpowerscripts:pool:fetch --tag <your-pool-tag> -v <your-dev-hub> -a <scratch-alias> -d`

**Expected behavior**
A scratch from the pool should be fetched and assigned as default scratch org.

**Platform Details (please complete the following information):**
 - OS: macOS Monterey Version 12.1
 - Version: sfpowerscripts 10.2.15
 - Salesforce CLI(sfdx cli) Version: 7.142.1
 - CI Platform: N/A (IDE Terminal)
 - Node Version: 16.13.1 (same with version 14.9)

**Comment by Schuchie** [comment]
Hey @ozanbotanls,
take a look into the following issue. Did you setup a remote (in git). I got a similar error on another command: https://github.com/Accenture/sfpowerscripts/issues/872#event-6160795806

**Comment by ozanbotanls** [comment]
@Schuchie I have seen that post too and gave it a try before opening this up. So It doesn't solve what I have here.
We did, however, try with alpha build upon a suggestion from @azlam-abdulsalam - it did work as expected.
So probably a dependency issue.

**Comment by azlam-abdulsalam** [comment]
Closing this as its a probably a dependency issue and not reproducible in recent version
