### ISSUE TITLE
Sudo command is missing in the latest version of docker container for sfpowerscripts

### ISSUE THREAD

**Issue by xpsp789** [dxatscale/sfpowerscripts#936]
**Describe the bug**
Running scripts using the sudo command shows (sudo: command not found).

**To Reproduce**
Run any script prefaced by sudo will cause it to fail with error sudo: command not found.

**Expected behavior**
The container would run the script prefaced by sudo.

**Screenshots**
![image](https://user-images.githubusercontent.com/74693968/163093453-402dab75-3d33-4a15-9da1-37d9839e929e.png)
**Platform Details (please complete the following information):**
 - OS: Ubuntu 20.04
 - Docker Version: [release-apr22,latest]
 - CI Platform: Azure Pipelines

**Additional context**
Workaround is to use previous version of the docker container as the issue is not present there.

**Comment by azlam-abdulsalam** [comment]
Fixed in Apr 22 - 2
