### ISSUE TITLE
scratch org dev pool not getting created

### ISSUE THREAD

**Issue by brijpandey7519** [dxatscale/sfpowerscripts#943]
**Describe the bug**
[Error: ENOENT: no such file or directory, rename '/root/.sfdx/sfdx.log' -> '/root/.sfdx/sfdx.log.0'] {

**To Reproduce**
Password successfully set for test-2drayydfppnv@example.com
Executing Preparation Job SO1 with username: test-zs9mmwfgqkww@example.com
Preparation Log files for test-zs9mmwfgqkww@example.com written to .sfpowerscripts/prepare_logs/SO1.log
Executing Preparation Job SO2 with username: test-2drayydfppnv@example.com
Preparation Log files for test-2drayydfppnv@example.com written to .sfpowerscripts/prepare_logs/SO2.log
Relaxing ip ranges for scratchOrg with user test-zs9mmwfgqkww@example.com
Relaxing ip ranges for scratchOrg with user test-2drayydfppnv@example.com
Installing Package Dependencies of this repo in SO1
Installing Package Dependencies of this repo in SO2
Successfully completed Installing Package Dependencies of this repo in SO1
Deploying all packages in the repo to  SO1
[Error: ENOENT: no such file or directory, rename '/root/.sfdx/sfdx.log' -> '/root/.sfdx/sfdx.log.0'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'rename',
  path: '/root/.sfdx/sfdx.log',
  dest: '/root/.sfdx/sfdx.log.0'
}
[Error: ENOENT: no such file or directory, rename '/root/.sfdx/sfdx.log' -> '/root/.sfdx/sfdx.log.0'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'rename',
  path: '/root/.sfdx/sfdx.log',
  dest: '/root/.sfdx/sfdx.log.0'
}

**Expected behavior**
Scratch org should be available
**Screenshots**

**Platform Details (please complete the following information):**
 - OS: 
 - Version [e.g. CLI Version  eg: 1.6.6]
 - Salesforce CLI(sfdx cli) Version:
 - CI Platform: 

**Additional context**
Er

**Comment by azlam-abdulsalam** [comment]
@brijpandey7519  Can you provide more details?
- OS?
- sfdx cli version?
- Docker?

**Comment by azlam-abdulsalam** [comment]
@brijpandey7519  any updates?

**Comment by vuha-acn** [comment]
@azlam-abdulsalam @brijpandey7519 - I believe this was resolved internally due to faulty packaging folder or dependencies issues with the codebase during a merge.  Will wait to hear back from @brijpandey7519  to confirm.

**Comment by brijpandey7519** [comment]
Hi Vu/Azlam,

Yes, issue was due to one of the guided scripts package went faulty as Vu mentioned, issue is resolved now.

I will open another case with issue we are having current sfdx-cli version 7.145.0/sfpowerkit 4.2.5  while creating scratch org where it's creating wrong JSON ( with extra brace and quotes) which is causing scratch org fetch command to fail and after manual fix of the json file , next time it's creating folder ( under .sfdx/orgs) with ORG name instead of with username and am only seeing maxRevision.json ( earlier version it was creating 3 files) and not generating sourcetrackingfiles on Scratch org under static resources.

Thanks much for the quick response.

Warm Regards,
Brij Pandey
+1-416-569-9896
