### ISSUE TITLE
lwc subdirectories not supported

### ISSUE THREAD

**Issue by yippie** [dxatscale/sfpowerscripts#959]
**Describe the bug**
sfpowerscripts seems to have the same issue that the latest versions of the sfdx cli has where lwc sub directories that used to work are now causing errors.

Behavior is identical to https://github.com/forcedotcom/cli/issues/1477

However, I am running an older version of the SFDX CLI that does not have the above issue in it.

**To Reproduce**
1) Have a source based project with the LWC in a folder structure like this:
lwc
+--folder1
| \ --lwc
| +--myLwcCmp1
| \ --myLwcCmp2
\--myLwcCmp3

2) run `sfdx sfpowerscripts:orchestrator:validate`

**Expected behavior**
Source to be deployed to the scratch org for validation. Instead getting `No base file for markup` errors

**Platform Details (please complete the following information):**
OS: macOS 12.3.1
Version: @dxatscale/sfpowerscripts 13.0.14
sfdmu 4.13.0
sfpowerkit 4.2.5
Salesforce CLI(sfdx cli) Version:sfdx-cli/7.143.0 darwin-arm64 node-v16.14.2

**Comment by azlam-abdulsalam** [comment]
Thanks @yippie . Looks like its fixed in 5.12.12 of SDR,  will plan a hotfix

**Comment by azlam-abdulsalam** [comment]
Fixed in alpha, will patch latest after tests
