### ISSUE TITLE
Component Diff Library

### ISSUE THREAD

**Issue by aly76** [dxatscale/sfpowerscripts#961]
sfpowerkit and sfpowerscripts have a shared requirement for a component diff. In sfpowerkit, the `project:diff` command uses a `git diff` to get the changed components between two commits. Likewise, sfpowerscripts uses `git diff` to get the changed components for a deployment. Therefore, it makes sense to create a component diff library, that both packages can use, so that code duplication is eliminated. Further, the library can be augmented so that it provides source components, and not just the filenames of changed components, and also provide information about the type of change - which will be useful for generating destructive manifests between two commits.

**Comment by azlam-abdulsalam** [comment]
Marked as stale! and not required as other functionalities in the core library provide similar features easily
