### ISSUE TITLE
fatal: bad object error on validation

### ISSUE THREAD

**Issue by gretarvp** [dxatscale/sfpowerscripts#965]
**Describe the bug**
If we run the command >sfdx sfpowerscripts:orchestrator:validate for a branch that does not contain the commit id the validation scratch org was created from we get the following error:

Checking last known tags for mdapiPre to determine whether package is to be built...
Utilizing tag a1f3ec6a9632778aac29e370ba05e43a43f9e4a9 for mdapiPre
Deleting scratch org [test-7kua9uyoq5ey@example.com](mailto:test-7kua9uyoq5ey@example.com)
fatal: bad object a1f3ec6a9632778aac29e370ba05e43a43f9e4a9

When the validation scratch org pool is updated frequently it can contain scratch orgs that are built on commits that are not in your feature branch because you created that branch before the scratch org was created. If you then run the validation without rebasing or merging the integration branch you branched the feature branch from into your feature branch then you will get this error

**To Reproduce**
1. Create a feature branch from an integration branch.
2. Commit new changes to the integration branch.
3. Create a validation scratch org pool from the integration branch.
4. Commit new changes to the feature branch and run the sfdx sfpowerscripts:orchestrator:validate command.

**Expected behavior**
A more descriptive error of why the command is failing instead of displaying "fatal: bad object".  This message could be e.g. "The commit <commit id from scratch org> was not found in your branch git history"

Because the command fails in the beginning it would help to not delete the scratch org but to make it available for another run of the validation command.

**Platform Details (please complete the following information):**
 - OS: Alpine Linux
 - Version: sfpowerscripts  -- The DX@Scale CI/CD Orchestrator -Version:13.0.12 -Release:April 22
 - Salesforce CLI(sfdx cli) Version: sfdx-cli@7.146.1
 - CI Platform: Bitbucket

**Comment by azlam-abdulsalam** [comment]
Thanks @gretarvp  Will fix the error message in next release

**Comment by gretarvp** [comment]
Good to hear, thank you :D
