### ISSUE TITLE
Error when running sfdx sfpowerscripts:package:unlocked:create

### ISSUE THREAD

**Issue by lotusboy** [dxatscale/sfpowerscripts#966]
**Describe the bug**

I have already run sfdx force:package:create for 3 unlocked packages as can be seen when I run:

sloftus@UKLDNPC0103 smartchassis % sfdx force:package:list -v devhub
=== Packages [3]
Namespace Prefix  Name                  Id                  Alias                 Description  Type
────────────────  ────────────────────  ──────b────────────  ────────────────────  ───────────  ────────
                  src-core              0Ho7Q000000PAypSAG  src-core                           Unlocked
                  src-env-specific-pre  0Ho7Q000000PAykSAG  src-env-specific-pre               Unlocked
                  src-ui                0Ho7Q000000PAyuSAG  src-ui                             Unlocked

then when I run the following I get the error:

sloftus@UKLDNPC0103 smartchassis % sfdx sfpowerscripts:package:unlocked:create -n src-env-specific-pre -v devhub -x --loglevel trace
-------------------------------------------------------------------------------------------
sfpowerscripts  -- The DX@Scale CI/CD Orchestrator -Version:13.0.14 -Release:April 22
-------------------------------------------------------------------------------------------
command: create  package
package name: src-env-specific-pre
package type: unlocked
package directory: ./src-env-specific-pre
-------------------------------------------------------------------------------------------
Source converted successfully to /Users/sloftus/Documents/git/smartchassis/.sfpowerscripts/r6IK0_source/.sfpowerscripts/r7NU3_mdapi
ConvertResult:{"packagePath":"/Users/sloftus/Documents/git/smartchassis/.sfpowerscripts/r6IK0_source/.sfpowerscripts/r7NU3_mdapi/metadataPackage_1651657658214","converted":[]}
Fetching Package Type Info from DevHub
Package  src-env-specific-pre
IsOrgDependent No
Package Id  0Ho7Q000000PAykSAG
-------------------------
Resolving project dependencies
Resolved Depenendecies: -------------------------------------------------------------------------------------------
sfpowerkit  -- The DX@Scale Developer Toolkit - Version:4.2.5 - Release:April 22
-------------------------------------------------------------------------------------------

No dependencies found for package directory ./src-env-specific-pre

Generated Command:sfdx force:package:version:create --json -p src-env-specific-pre  -w 120 --definitionfile config/project-scratch-def.json -x -c -v sloftus@pboedition.com
Error: {
  "status": 1,
  "name": "Error",
  "message": "An unexpected error occurred while preparing endpoint: C-9999.  Please contact Salesforce Support and provide the following error code: 1788837751-44548 (-1143416155)",
  "exitCode": 1,
  "commandName": "PackageVersionCreateCommand",
  "stack": "Error: An unexpected error occurred while preparing endpoint: C-9999.  Please contact Salesforce Support and provide the following error code: 1788837751-44548 (-1143416155)\n    at /usr/local/lib/node_modules/sfdx-cli/node_modules/salesforce-alm/dist/lib/package/packageUtils.js:736:27\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\nOuter stack:\n    at Function.wrap (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/core/lib/sfdxError.js:171:27)\n    at PackageVersionCreateCommand.catch (/usr/local/lib/node_modules/sfdx-cli/node_modules/salesforce-alm/dist/ToolbeltCommand.js:253:46)\n    at async PackageVersionCreateCommand._run (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/command/lib/sfdxCommand.js:85:13)\n    at async Config.runCommand (/usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/config/lib/config.js:173:24)\n    at async SfdxMain.run (/usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/command/lib/main.js:27:9)\n    at async SfdxMain._run (/usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/command/lib/command.js:43:20)\n    at async Object.run (/usr/local/lib/node_modules/sfdx-cli/dist/cli.js:162:47)",
  "warnings": []
}

    at ChildProcess.<anonymous> (/Users/sloftus/.local/share/sfdx/node_modules/@dxatscale/sfpowerscripts.core/lib/command/commandExecutor/ExecuteCommand.js:64:36)
    at Object.onceWrapper (node:events:510:26)
    at ChildProcess.emit (node:events:402:35)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)

**To Reproduce**

- create a new unlocked package in a devhub using force:package:create
- attempt to create a version of that package using sfpowerscripts:package:unlocked:create
- receive unexpected error

**Expected behavior**

- expected a version of my unlocked package to be created but instead get an error 
sloftus@UKLDNPC0103 smartchassis % sfdx force:package:version:create:list -v devhub                                   
=== Package Version Create Requests  [14]
Id                  Status  Package Id          Package Version Id  Subscriber Package Version Id  Tag  Branch  Created Date      Created By
──────────────────  ──────  ──────────────────  ──────────────────  ─────────────────────────────  ───  ──────  ────────────────  ──────────────────
08c7Q000000PBACQA4  Error   0Ho7Q000000PAykSAG                                                                  2022-05-04 09:20  0057Q000004757HQAQ
08c7Q000000PBAHQA4  Error   0Ho7Q000000PAykSAG                                                                  2022-05-04 09:27  0057Q000004757HQAQ
08c7Q000000PBAMQA4  Error   0Ho7Q000000PAykSAG                                                                  2022-05-04 10:47  0057Q000004757HQAQ

**Platform Details (please complete the following information):**

sloftus@UKLDNPC0103 smartchassis % sfdx --version
sfdx-cli/7.142.1 darwin-x64 node-v16.13.1

**Comment by azlam-abdulsalam** [comment]
@lotusboy This is an issue with Salesforce
