### ISSUE TITLE
Issue when publishing artifacts to Azure Artifacts

### ISSUE THREAD

**Issue by zhebinliu** [dxatscale/sfpowerscripts#967]
**Describe the bug**
There is an issue when publishing the artifacts to Azure Artifacts

sfpowerscripts  -- The DX@Scale CI/CD Orchestrator -Version:13.3.1 -Release:May 22
-------------------------------------------------------------------------------------------
command: publish
target: NPM
Publish promoted artifacts only: false
-------------------------------------------------------------------------------------------
Publishing xxxxx Version 14.0.0-14 with tag develop_h2r6...
spawnSync /bin/sh ENOBUFS
----------------------------------------------------------------------------------------------------
0 artifacts published in 00:00:06 with {1} errors
Packages Failed to Publish xxxxx v14.0.0-14
----------------------------------------------------------------------------------------------------
##[error]Bash exited with code '1'.

**To Reproduce**
re-run the pipeline with command  
sfdx sfpowerscripts:orchestrator:publish -d artifacts --npm --scope $(SCOPE) --npmrcpath .npmrc --npmtag $(Build.SourceBranchName) --gittag --pushgittag

**Expected behavior**
Publish successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/85538531/166849162-c1af6aa3-53b3-45e4-9421-304c97c00595.png)

**Platform Details (please complete the following information):**
 - OS: Ubuntu 20.04
 - Salesforce CLI(sfdx cli) Version: 7.145.0
 - CI Platform: Azure DevOps

**Comment by calvinle1** [comment]
Hi, this might assist with triage: https://stackoverflow.com/questions/63796633/spawnsync-bin-sh-enobufs

**Comment by azlam-abdulsalam** [comment]
Fixed in May 22
