### ISSUE TITLE
[New Feature]: Specify Artifacts to be Installed in Pools

### ISSUE THREAD

**Issue by ozanbotanls** [dxatscale/sfpowerscripts#978]
**Describe the feature**

- A pool should be able to be created with the desired artifacts. 
- That includes managed package dependencies as well as unlocked, source, or data packages.
- As long as the specified set of artifacts is compiled and able to be built with no dependency issues, any given combination of artifacts should be deployable in pools.

**Assumptions;**
- Project is a mono repo.
- There are no multiple branches maintained per team, feature, domain, etc. The main trunk is the source of truth.

**Why?**
- There are different teams working on the monolith based on business domains. Oftentimes, one team has nothing to do with some of the managed package dependencies as well as unlocked or source packages. 
- Business wants a demo showcasing a specific application domain. We should be able to define a demo pool that has only what needs to be there.

How?
- A new attribute can be exposed as part of pool configuration json where the desired dependencies and artifacts can be provided.
- This can be also done over multiple sfdx-project.json definitions. 
- How to avoid project json conflicts between different teams is a catch here.

**Comment by domrycz** [comment]
Hey @azlam-abdulsalam , do you have any idea which version/release will include this feature?

**Comment by azlam-abdulsalam** [comment]
@domrycz  We haven't slotted this to a release yet
