### ISSUE TITLE
aura in subfolders no longer work in force:source:push and force:source:deploy

### ISSUE THREAD

**Issue by zhebinliu** [dxatscale/sfpowerscripts#990]
**Describe the bug**
sfpowerscript no longer supports aura subfolders in the source code in prepare and validate command.  this worked just fine with dec21 release

**To Reproduce**
Have a source based project with the aurain a folder structure like this:
aura
+--folder1
| \ --aura
| +--myAuraCmp1
| \ --myAuraCmp2
--myAuraCmp3

**Expected behavior**
Deploy Errors:
Failed to handle component xxxxx, file path not expected

**Platform Details (please complete the following information):**
System Information
{
"cliVersion": "sfdx-cli/7.145.0",
"architecture": "win32-x64",
"nodeVersion": "node-v16.14.2",
"osVersion": "Windows 11"
}
 
forcedorcome/cli issue link: https://github.com/forcedotcom/cli/issues/1541

**Comment by azlam-abdulsalam** [comment]
Closing this as mentioned in the cli issue
