### ISSUE TITLE
orchestrator:deploy error INVALID_OPERATION: testLevel of NoTestRun

### ISSUE THREAD

**Issue by mpaul1** [dxatscale/sfpowerscripts#992]
**Describe the bug**
When deploying to a Production org, this error occurs: Error: INVALID_OPERATION: testLevel of NoTestRun cannot be used in production organizations

Log Details:
Deployment Options
=================================================================================================
TestLevel: RunLocalTests
Ignore Warnings: true
Roll Back on Error: true
API Version: 54.0
=================================================================================================
Error: INVALID_OPERATION: testLevel of NoTestRun cannot be used in production organizations

**To Reproduce**
When running sfdx sfpowerscripts:orchestrator:deploy --tag 1234567.1 --skipifalreadyinstalled --artifactdir /promote -u Prod

**Expected behavior**
It should run RunLocalTests as specified in the deployment options.

**Platform Details (please complete the following information):**
 - OS: Linux
 -Fails with any versions higher than those specified below....  I have tried many combinations attempting to find one that works in Production.  This is NOT an issue running deployments in sandboxes.  I have tried with the sfdx-project.json properties set as "skipTesting": false and omitting this property completely in the project file.

Succeeds with these versions:
prod-sfdx-cli-version: 7.129.0
prod-sfpowerkitversion: 4.0.1
prod-sfpowerscriptsversion: 10.2.4
prod-sfdmuversion: 4.14.4

**Comment by azlam-abdulsalam** [comment]
Thanks @mpaul1 , Looking into it. Looks like a regression

I assume you want this package to be deployed with local tests as opposed to with in the package

**Comment by azlam-abdulsalam** [comment]
Thanks @mpaul1 , Looking into it. Looks like a regression

I assume you want this package to be deployed with local tests as opposed to with in the package
